/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateSubmissionRequestSubmittersInnerFieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionRequestSubmittersInnerFieldsInner{}

// CreateSubmissionRequestSubmittersInnerFieldsInner struct for CreateSubmissionRequestSubmittersInnerFieldsInner
type CreateSubmissionRequestSubmittersInnerFieldsInner struct {
	// Document template field name.
	Name         string                                                         `json:"name"`
	DefaultValue *CreateSubmissionRequestSubmittersInnerFieldsInnerDefaultValue `json:"default_value,omitempty"`
	// Set `true` to make it impossible for the submitter to edit predefined field value.
	Readonly *bool `json:"readonly,omitempty"`
	// Set `true` to make the field required.
	Required *bool `json:"required,omitempty"`
	// Field title displayed to the user instead of the name, shown on the signing form. Supports Markdown.
	Title *string `json:"title,omitempty"`
	// Field description displayed on the signing form. Supports Markdown.
	Description *string                                                       `json:"description,omitempty"`
	Validation  *CreateSubmissionRequestSubmittersInnerFieldsInnerValidation  `json:"validation,omitempty"`
	Preferences *CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences `json:"preferences,omitempty"`
}

type _CreateSubmissionRequestSubmittersInnerFieldsInner CreateSubmissionRequestSubmittersInnerFieldsInner

// NewCreateSubmissionRequestSubmittersInnerFieldsInner instantiates a new CreateSubmissionRequestSubmittersInnerFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionRequestSubmittersInnerFieldsInner(name string) *CreateSubmissionRequestSubmittersInnerFieldsInner {
	this := CreateSubmissionRequestSubmittersInnerFieldsInner{}
	this.Name = name
	var readonly bool = false
	this.Readonly = &readonly
	return &this
}

// NewCreateSubmissionRequestSubmittersInnerFieldsInnerWithDefaults instantiates a new CreateSubmissionRequestSubmittersInnerFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionRequestSubmittersInnerFieldsInnerWithDefaults() *CreateSubmissionRequestSubmittersInnerFieldsInner {
	this := CreateSubmissionRequestSubmittersInnerFieldsInner{}
	var readonly bool = false
	this.Readonly = &readonly
	return &this
}

// GetName returns the Name field value
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) SetName(v string) {
	o.Name = v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetDefaultValue() CreateSubmissionRequestSubmittersInnerFieldsInnerDefaultValue {
	if o == nil || IsNil(o.DefaultValue) {
		var ret CreateSubmissionRequestSubmittersInnerFieldsInnerDefaultValue
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetDefaultValueOk() (*CreateSubmissionRequestSubmittersInnerFieldsInnerDefaultValue, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given CreateSubmissionRequestSubmittersInnerFieldsInnerDefaultValue and assigns it to the DefaultValue field.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) SetDefaultValue(v CreateSubmissionRequestSubmittersInnerFieldsInnerDefaultValue) {
	o.DefaultValue = &v
}

// GetReadonly returns the Readonly field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetReadonly() bool {
	if o == nil || IsNil(o.Readonly) {
		var ret bool
		return ret
	}
	return *o.Readonly
}

// GetReadonlyOk returns a tuple with the Readonly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetReadonlyOk() (*bool, bool) {
	if o == nil || IsNil(o.Readonly) {
		return nil, false
	}
	return o.Readonly, true
}

// HasReadonly returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) HasReadonly() bool {
	if o != nil && !IsNil(o.Readonly) {
		return true
	}

	return false
}

// SetReadonly gets a reference to the given bool and assigns it to the Readonly field.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) SetReadonly(v bool) {
	o.Readonly = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) SetRequired(v bool) {
	o.Required = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) SetDescription(v string) {
	o.Description = &v
}

// GetValidation returns the Validation field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetValidation() CreateSubmissionRequestSubmittersInnerFieldsInnerValidation {
	if o == nil || IsNil(o.Validation) {
		var ret CreateSubmissionRequestSubmittersInnerFieldsInnerValidation
		return ret
	}
	return *o.Validation
}

// GetValidationOk returns a tuple with the Validation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetValidationOk() (*CreateSubmissionRequestSubmittersInnerFieldsInnerValidation, bool) {
	if o == nil || IsNil(o.Validation) {
		return nil, false
	}
	return o.Validation, true
}

// HasValidation returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) HasValidation() bool {
	if o != nil && !IsNil(o.Validation) {
		return true
	}

	return false
}

// SetValidation gets a reference to the given CreateSubmissionRequestSubmittersInnerFieldsInnerValidation and assigns it to the Validation field.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) SetValidation(v CreateSubmissionRequestSubmittersInnerFieldsInnerValidation) {
	o.Validation = &v
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetPreferences() CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences {
	if o == nil || IsNil(o.Preferences) {
		var ret CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences
		return ret
	}
	return *o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) GetPreferencesOk() (*CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences, bool) {
	if o == nil || IsNil(o.Preferences) {
		return nil, false
	}
	return o.Preferences, true
}

// HasPreferences returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) HasPreferences() bool {
	if o != nil && !IsNil(o.Preferences) {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences and assigns it to the Preferences field.
func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) SetPreferences(v CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences) {
	o.Preferences = &v
}

func (o CreateSubmissionRequestSubmittersInnerFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionRequestSubmittersInnerFieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.DefaultValue) {
		toSerialize["default_value"] = o.DefaultValue
	}
	if !IsNil(o.Readonly) {
		toSerialize["readonly"] = o.Readonly
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Validation) {
		toSerialize["validation"] = o.Validation
	}
	if !IsNil(o.Preferences) {
		toSerialize["preferences"] = o.Preferences
	}
	return toSerialize, nil
}

func (o *CreateSubmissionRequestSubmittersInnerFieldsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSubmissionRequestSubmittersInnerFieldsInner := _CreateSubmissionRequestSubmittersInnerFieldsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSubmissionRequestSubmittersInnerFieldsInner)

	if err != nil {
		return err
	}

	*o = CreateSubmissionRequestSubmittersInnerFieldsInner(varCreateSubmissionRequestSubmittersInnerFieldsInner)

	return err
}

type NullableCreateSubmissionRequestSubmittersInnerFieldsInner struct {
	value *CreateSubmissionRequestSubmittersInnerFieldsInner
	isSet bool
}

func (v NullableCreateSubmissionRequestSubmittersInnerFieldsInner) Get() *CreateSubmissionRequestSubmittersInnerFieldsInner {
	return v.value
}

func (v *NullableCreateSubmissionRequestSubmittersInnerFieldsInner) Set(val *CreateSubmissionRequestSubmittersInnerFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionRequestSubmittersInnerFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionRequestSubmittersInnerFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionRequestSubmittersInnerFieldsInner(val *CreateSubmissionRequestSubmittersInnerFieldsInner) *NullableCreateSubmissionRequestSubmittersInnerFieldsInner {
	return &NullableCreateSubmissionRequestSubmittersInnerFieldsInner{value: val, isSet: true}
}

func (v NullableCreateSubmissionRequestSubmittersInnerFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionRequestSubmittersInnerFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
