/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the CreateSubmissionRequestSubmittersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionRequestSubmittersInner{}

// CreateSubmissionRequestSubmittersInner struct for CreateSubmissionRequestSubmittersInner
type CreateSubmissionRequestSubmittersInner struct {
	// The name of the submitter.
	Name *string `json:"name,omitempty"`
	// The role name or title of the submitter.
	Role *string `json:"role,omitempty"`
	// The email address of the submitter.
	Email *string `json:"email,omitempty"`
	// The phone number of the submitter, formatted according to the E.164 standard.
	Phone *string `json:"phone,omitempty"`
	// An object with pre-filled values for the submission. Use field names for keys of the object. For more configurations see `fields` param.
	Values map[string]interface{} `json:"values,omitempty"`
	// Your application-specific unique string key to identify this submitter within your app.
	ExternalId *string `json:"external_id,omitempty"`
	// Pass `true` to mark submitter as completed and auto-signed via API.
	Completed *bool `json:"completed,omitempty"`
	// Metadata object with additional submitter information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Set `false` to disable signature request emails sending only for this submitter.
	SendEmail *bool `json:"send_email,omitempty"`
	// Set `true` to send signature request via phone number and SMS.
	SendSms *bool `json:"send_sms,omitempty"`
	// Specify Reply-To address to use in the notification emails for this submitter.
	ReplyTo *string `json:"reply_to,omitempty"`
	// Submitter specific URL to redirect to after the submission completion.
	CompletedRedirectUrl *string `json:"completed_redirect_url,omitempty"`
	// The order of the submitter in the workflow (e.g., 0 for the first signer, 1 for the second, etc.). Use the same order number to create order groups. By default, submitters are ordered as in the submitters array.
	Order *int32 `json:"order,omitempty"`
	// Set to `true` to require phone 2FA verification via a one-time code sent to the phone number in order to access the documents.
	RequirePhone2fa *bool `json:"require_phone_2fa,omitempty"`
	// Set to `true` to require email 2FA verification via a one-time code sent to the email address in order to access the documents.
	RequireEmail2fa *bool                           `json:"require_email_2fa,omitempty"`
	Message         *CreateSubmissionRequestMessage `json:"message,omitempty"`
	// A list of configurations for template document form fields.
	Fields []CreateSubmissionRequestSubmittersInnerFieldsInner `json:"fields,omitempty"`
	// A list of roles for the submitter. Use this param to merge multiple roles into one submitter.
	Roles []string `json:"roles,omitempty"`
}

// NewCreateSubmissionRequestSubmittersInner instantiates a new CreateSubmissionRequestSubmittersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionRequestSubmittersInner() *CreateSubmissionRequestSubmittersInner {
	this := CreateSubmissionRequestSubmittersInner{}
	var sendEmail bool = true
	this.SendEmail = &sendEmail
	var sendSms bool = false
	this.SendSms = &sendSms
	var requirePhone2fa bool = false
	this.RequirePhone2fa = &requirePhone2fa
	var requireEmail2fa bool = false
	this.RequireEmail2fa = &requireEmail2fa
	return &this
}

// NewCreateSubmissionRequestSubmittersInnerWithDefaults instantiates a new CreateSubmissionRequestSubmittersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionRequestSubmittersInnerWithDefaults() *CreateSubmissionRequestSubmittersInner {
	this := CreateSubmissionRequestSubmittersInner{}
	var sendEmail bool = true
	this.SendEmail = &sendEmail
	var sendSms bool = false
	this.SendSms = &sendSms
	var requirePhone2fa bool = false
	this.RequirePhone2fa = &requirePhone2fa
	var requireEmail2fa bool = false
	this.RequireEmail2fa = &requireEmail2fa
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateSubmissionRequestSubmittersInner) SetName(v string) {
	o.Name = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *CreateSubmissionRequestSubmittersInner) SetRole(v string) {
	o.Role = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CreateSubmissionRequestSubmittersInner) SetEmail(v string) {
	o.Email = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *CreateSubmissionRequestSubmittersInner) SetPhone(v string) {
	o.Phone = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetValues() map[string]interface{} {
	if o == nil || IsNil(o.Values) {
		var ret map[string]interface{}
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetValuesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Values) {
		return map[string]interface{}{}, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]interface{} and assigns it to the Values field.
func (o *CreateSubmissionRequestSubmittersInner) SetValues(v map[string]interface{}) {
	o.Values = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *CreateSubmissionRequestSubmittersInner) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetCompleted returns the Completed field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetCompleted() bool {
	if o == nil || IsNil(o.Completed) {
		var ret bool
		return ret
	}
	return *o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetCompletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Completed) {
		return nil, false
	}
	return o.Completed, true
}

// HasCompleted returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasCompleted() bool {
	if o != nil && !IsNil(o.Completed) {
		return true
	}

	return false
}

// SetCompleted gets a reference to the given bool and assigns it to the Completed field.
func (o *CreateSubmissionRequestSubmittersInner) SetCompleted(v bool) {
	o.Completed = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CreateSubmissionRequestSubmittersInner) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetSendEmail returns the SendEmail field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetSendEmail() bool {
	if o == nil || IsNil(o.SendEmail) {
		var ret bool
		return ret
	}
	return *o.SendEmail
}

// GetSendEmailOk returns a tuple with the SendEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetSendEmailOk() (*bool, bool) {
	if o == nil || IsNil(o.SendEmail) {
		return nil, false
	}
	return o.SendEmail, true
}

// HasSendEmail returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasSendEmail() bool {
	if o != nil && !IsNil(o.SendEmail) {
		return true
	}

	return false
}

// SetSendEmail gets a reference to the given bool and assigns it to the SendEmail field.
func (o *CreateSubmissionRequestSubmittersInner) SetSendEmail(v bool) {
	o.SendEmail = &v
}

// GetSendSms returns the SendSms field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetSendSms() bool {
	if o == nil || IsNil(o.SendSms) {
		var ret bool
		return ret
	}
	return *o.SendSms
}

// GetSendSmsOk returns a tuple with the SendSms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetSendSmsOk() (*bool, bool) {
	if o == nil || IsNil(o.SendSms) {
		return nil, false
	}
	return o.SendSms, true
}

// HasSendSms returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasSendSms() bool {
	if o != nil && !IsNil(o.SendSms) {
		return true
	}

	return false
}

// SetSendSms gets a reference to the given bool and assigns it to the SendSms field.
func (o *CreateSubmissionRequestSubmittersInner) SetSendSms(v bool) {
	o.SendSms = &v
}

// GetReplyTo returns the ReplyTo field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetReplyTo() string {
	if o == nil || IsNil(o.ReplyTo) {
		var ret string
		return ret
	}
	return *o.ReplyTo
}

// GetReplyToOk returns a tuple with the ReplyTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetReplyToOk() (*string, bool) {
	if o == nil || IsNil(o.ReplyTo) {
		return nil, false
	}
	return o.ReplyTo, true
}

// HasReplyTo returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasReplyTo() bool {
	if o != nil && !IsNil(o.ReplyTo) {
		return true
	}

	return false
}

// SetReplyTo gets a reference to the given string and assigns it to the ReplyTo field.
func (o *CreateSubmissionRequestSubmittersInner) SetReplyTo(v string) {
	o.ReplyTo = &v
}

// GetCompletedRedirectUrl returns the CompletedRedirectUrl field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetCompletedRedirectUrl() string {
	if o == nil || IsNil(o.CompletedRedirectUrl) {
		var ret string
		return ret
	}
	return *o.CompletedRedirectUrl
}

// GetCompletedRedirectUrlOk returns a tuple with the CompletedRedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetCompletedRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CompletedRedirectUrl) {
		return nil, false
	}
	return o.CompletedRedirectUrl, true
}

// HasCompletedRedirectUrl returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasCompletedRedirectUrl() bool {
	if o != nil && !IsNil(o.CompletedRedirectUrl) {
		return true
	}

	return false
}

// SetCompletedRedirectUrl gets a reference to the given string and assigns it to the CompletedRedirectUrl field.
func (o *CreateSubmissionRequestSubmittersInner) SetCompletedRedirectUrl(v string) {
	o.CompletedRedirectUrl = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *CreateSubmissionRequestSubmittersInner) SetOrder(v int32) {
	o.Order = &v
}

// GetRequirePhone2fa returns the RequirePhone2fa field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetRequirePhone2fa() bool {
	if o == nil || IsNil(o.RequirePhone2fa) {
		var ret bool
		return ret
	}
	return *o.RequirePhone2fa
}

// GetRequirePhone2faOk returns a tuple with the RequirePhone2fa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetRequirePhone2faOk() (*bool, bool) {
	if o == nil || IsNil(o.RequirePhone2fa) {
		return nil, false
	}
	return o.RequirePhone2fa, true
}

// HasRequirePhone2fa returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasRequirePhone2fa() bool {
	if o != nil && !IsNil(o.RequirePhone2fa) {
		return true
	}

	return false
}

// SetRequirePhone2fa gets a reference to the given bool and assigns it to the RequirePhone2fa field.
func (o *CreateSubmissionRequestSubmittersInner) SetRequirePhone2fa(v bool) {
	o.RequirePhone2fa = &v
}

// GetRequireEmail2fa returns the RequireEmail2fa field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetRequireEmail2fa() bool {
	if o == nil || IsNil(o.RequireEmail2fa) {
		var ret bool
		return ret
	}
	return *o.RequireEmail2fa
}

// GetRequireEmail2faOk returns a tuple with the RequireEmail2fa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetRequireEmail2faOk() (*bool, bool) {
	if o == nil || IsNil(o.RequireEmail2fa) {
		return nil, false
	}
	return o.RequireEmail2fa, true
}

// HasRequireEmail2fa returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasRequireEmail2fa() bool {
	if o != nil && !IsNil(o.RequireEmail2fa) {
		return true
	}

	return false
}

// SetRequireEmail2fa gets a reference to the given bool and assigns it to the RequireEmail2fa field.
func (o *CreateSubmissionRequestSubmittersInner) SetRequireEmail2fa(v bool) {
	o.RequireEmail2fa = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetMessage() CreateSubmissionRequestMessage {
	if o == nil || IsNil(o.Message) {
		var ret CreateSubmissionRequestMessage
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetMessageOk() (*CreateSubmissionRequestMessage, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given CreateSubmissionRequestMessage and assigns it to the Message field.
func (o *CreateSubmissionRequestSubmittersInner) SetMessage(v CreateSubmissionRequestMessage) {
	o.Message = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetFields() []CreateSubmissionRequestSubmittersInnerFieldsInner {
	if o == nil || IsNil(o.Fields) {
		var ret []CreateSubmissionRequestSubmittersInnerFieldsInner
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetFieldsOk() ([]CreateSubmissionRequestSubmittersInnerFieldsInner, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []CreateSubmissionRequestSubmittersInnerFieldsInner and assigns it to the Fields field.
func (o *CreateSubmissionRequestSubmittersInner) SetFields(v []CreateSubmissionRequestSubmittersInnerFieldsInner) {
	o.Fields = v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *CreateSubmissionRequestSubmittersInner) GetRoles() []string {
	if o == nil || IsNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestSubmittersInner) GetRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *CreateSubmissionRequestSubmittersInner) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *CreateSubmissionRequestSubmittersInner) SetRoles(v []string) {
	o.Roles = v
}

func (o CreateSubmissionRequestSubmittersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionRequestSubmittersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !IsNil(o.Completed) {
		toSerialize["completed"] = o.Completed
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.SendEmail) {
		toSerialize["send_email"] = o.SendEmail
	}
	if !IsNil(o.SendSms) {
		toSerialize["send_sms"] = o.SendSms
	}
	if !IsNil(o.ReplyTo) {
		toSerialize["reply_to"] = o.ReplyTo
	}
	if !IsNil(o.CompletedRedirectUrl) {
		toSerialize["completed_redirect_url"] = o.CompletedRedirectUrl
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.RequirePhone2fa) {
		toSerialize["require_phone_2fa"] = o.RequirePhone2fa
	}
	if !IsNil(o.RequireEmail2fa) {
		toSerialize["require_email_2fa"] = o.RequireEmail2fa
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	return toSerialize, nil
}

type NullableCreateSubmissionRequestSubmittersInner struct {
	value *CreateSubmissionRequestSubmittersInner
	isSet bool
}

func (v NullableCreateSubmissionRequestSubmittersInner) Get() *CreateSubmissionRequestSubmittersInner {
	return v.value
}

func (v *NullableCreateSubmissionRequestSubmittersInner) Set(val *CreateSubmissionRequestSubmittersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionRequestSubmittersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionRequestSubmittersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionRequestSubmittersInner(val *CreateSubmissionRequestSubmittersInner) *NullableCreateSubmissionRequestSubmittersInner {
	return &NullableCreateSubmissionRequestSubmittersInner{value: val, isSet: true}
}

func (v NullableCreateSubmissionRequestSubmittersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionRequestSubmittersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
