/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the CreateTemplateFromDocxRequestDocumentsInnerFieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTemplateFromDocxRequestDocumentsInnerFieldsInner{}

// CreateTemplateFromDocxRequestDocumentsInnerFieldsInner struct for CreateTemplateFromDocxRequestDocumentsInnerFieldsInner
type CreateTemplateFromDocxRequestDocumentsInnerFieldsInner struct {
	// Name of the field.
	Name *string `json:"name,omitempty"`
	// Type of the field (e.g., text, signature, date, initials).
	Type *string `json:"type,omitempty"`
	// Role name of the signer.
	Role *string `json:"role,omitempty"`
	// Indicates if the field is required.
	Required *bool `json:"required,omitempty"`
	// Field title displayed to the user instead of the name, shown on the signing form. Supports Markdown.
	Title *string `json:"title,omitempty"`
	// Field description displayed on the signing form. Supports Markdown.
	Description *string `json:"description,omitempty"`
	// List of areas where the field is located in the document.
	Areas []CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner `json:"areas,omitempty"`
	// An array of option values for 'select' field type.
	Options     []string                                                      `json:"options,omitempty"`
	Validation  *CreateSubmissionRequestSubmittersInnerFieldsInnerValidation  `json:"validation,omitempty"`
	Preferences *CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences `json:"preferences,omitempty"`
}

// NewCreateTemplateFromDocxRequestDocumentsInnerFieldsInner instantiates a new CreateTemplateFromDocxRequestDocumentsInnerFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTemplateFromDocxRequestDocumentsInnerFieldsInner() *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner {
	this := CreateTemplateFromDocxRequestDocumentsInnerFieldsInner{}
	return &this
}

// NewCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerWithDefaults instantiates a new CreateTemplateFromDocxRequestDocumentsInnerFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerWithDefaults() *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner {
	this := CreateTemplateFromDocxRequestDocumentsInnerFieldsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) SetType(v string) {
	o.Type = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) SetRole(v string) {
	o.Role = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) SetRequired(v bool) {
	o.Required = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) SetDescription(v string) {
	o.Description = &v
}

// GetAreas returns the Areas field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetAreas() []CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner {
	if o == nil || IsNil(o.Areas) {
		var ret []CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner
		return ret
	}
	return o.Areas
}

// GetAreasOk returns a tuple with the Areas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetAreasOk() ([]CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner, bool) {
	if o == nil || IsNil(o.Areas) {
		return nil, false
	}
	return o.Areas, true
}

// HasAreas returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) HasAreas() bool {
	if o != nil && !IsNil(o.Areas) {
		return true
	}

	return false
}

// SetAreas gets a reference to the given []CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner and assigns it to the Areas field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) SetAreas(v []CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) {
	o.Areas = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetOptions() []string {
	if o == nil || IsNil(o.Options) {
		var ret []string
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetOptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []string and assigns it to the Options field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) SetOptions(v []string) {
	o.Options = v
}

// GetValidation returns the Validation field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetValidation() CreateSubmissionRequestSubmittersInnerFieldsInnerValidation {
	if o == nil || IsNil(o.Validation) {
		var ret CreateSubmissionRequestSubmittersInnerFieldsInnerValidation
		return ret
	}
	return *o.Validation
}

// GetValidationOk returns a tuple with the Validation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetValidationOk() (*CreateSubmissionRequestSubmittersInnerFieldsInnerValidation, bool) {
	if o == nil || IsNil(o.Validation) {
		return nil, false
	}
	return o.Validation, true
}

// HasValidation returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) HasValidation() bool {
	if o != nil && !IsNil(o.Validation) {
		return true
	}

	return false
}

// SetValidation gets a reference to the given CreateSubmissionRequestSubmittersInnerFieldsInnerValidation and assigns it to the Validation field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) SetValidation(v CreateSubmissionRequestSubmittersInnerFieldsInnerValidation) {
	o.Validation = &v
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetPreferences() CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences {
	if o == nil || IsNil(o.Preferences) {
		var ret CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences
		return ret
	}
	return *o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) GetPreferencesOk() (*CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences, bool) {
	if o == nil || IsNil(o.Preferences) {
		return nil, false
	}
	return o.Preferences, true
}

// HasPreferences returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) HasPreferences() bool {
	if o != nil && !IsNil(o.Preferences) {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences and assigns it to the Preferences field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) SetPreferences(v CreateSubmissionRequestSubmittersInnerFieldsInnerPreferences) {
	o.Preferences = &v
}

func (o CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Areas) {
		toSerialize["areas"] = o.Areas
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	if !IsNil(o.Validation) {
		toSerialize["validation"] = o.Validation
	}
	if !IsNil(o.Preferences) {
		toSerialize["preferences"] = o.Preferences
	}
	return toSerialize, nil
}

type NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInner struct {
	value *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner
	isSet bool
}

func (v NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInner) Get() *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner {
	return v.value
}

func (v *NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInner) Set(val *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInner(val *CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) *NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInner {
	return &NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInner{value: val, isSet: true}
}

func (v NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
