/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateTemplateFromPdfRequestDocumentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTemplateFromPdfRequestDocumentsInner{}

// CreateTemplateFromPdfRequestDocumentsInner struct for CreateTemplateFromPdfRequestDocumentsInner
type CreateTemplateFromPdfRequestDocumentsInner struct {
	// Name of the document.
	Name string `json:"name"`
	// Base64-encoded content of the PDF file or downloadable file URL.
	File string `json:"file"`
	// Fields are optional if you use {{...}} text tags to define fields in the document.
	Fields []CreateTemplateFromPdfRequestDocumentsInnerFieldsInner `json:"fields,omitempty"`
}

type _CreateTemplateFromPdfRequestDocumentsInner CreateTemplateFromPdfRequestDocumentsInner

// NewCreateTemplateFromPdfRequestDocumentsInner instantiates a new CreateTemplateFromPdfRequestDocumentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTemplateFromPdfRequestDocumentsInner(name string, file string) *CreateTemplateFromPdfRequestDocumentsInner {
	this := CreateTemplateFromPdfRequestDocumentsInner{}
	this.Name = name
	this.File = file
	return &this
}

// NewCreateTemplateFromPdfRequestDocumentsInnerWithDefaults instantiates a new CreateTemplateFromPdfRequestDocumentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTemplateFromPdfRequestDocumentsInnerWithDefaults() *CreateTemplateFromPdfRequestDocumentsInner {
	this := CreateTemplateFromPdfRequestDocumentsInner{}
	return &this
}

// GetName returns the Name field value
func (o *CreateTemplateFromPdfRequestDocumentsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromPdfRequestDocumentsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTemplateFromPdfRequestDocumentsInner) SetName(v string) {
	o.Name = v
}

// GetFile returns the File field value
func (o *CreateTemplateFromPdfRequestDocumentsInner) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromPdfRequestDocumentsInner) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *CreateTemplateFromPdfRequestDocumentsInner) SetFile(v string) {
	o.File = v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *CreateTemplateFromPdfRequestDocumentsInner) GetFields() []CreateTemplateFromPdfRequestDocumentsInnerFieldsInner {
	if o == nil || IsNil(o.Fields) {
		var ret []CreateTemplateFromPdfRequestDocumentsInnerFieldsInner
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromPdfRequestDocumentsInner) GetFieldsOk() ([]CreateTemplateFromPdfRequestDocumentsInnerFieldsInner, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *CreateTemplateFromPdfRequestDocumentsInner) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []CreateTemplateFromPdfRequestDocumentsInnerFieldsInner and assigns it to the Fields field.
func (o *CreateTemplateFromPdfRequestDocumentsInner) SetFields(v []CreateTemplateFromPdfRequestDocumentsInnerFieldsInner) {
	o.Fields = v
}

func (o CreateTemplateFromPdfRequestDocumentsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTemplateFromPdfRequestDocumentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["file"] = o.File
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	return toSerialize, nil
}

func (o *CreateTemplateFromPdfRequestDocumentsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"file",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTemplateFromPdfRequestDocumentsInner := _CreateTemplateFromPdfRequestDocumentsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTemplateFromPdfRequestDocumentsInner)

	if err != nil {
		return err
	}

	*o = CreateTemplateFromPdfRequestDocumentsInner(varCreateTemplateFromPdfRequestDocumentsInner)

	return err
}

type NullableCreateTemplateFromPdfRequestDocumentsInner struct {
	value *CreateTemplateFromPdfRequestDocumentsInner
	isSet bool
}

func (v NullableCreateTemplateFromPdfRequestDocumentsInner) Get() *CreateTemplateFromPdfRequestDocumentsInner {
	return v.value
}

func (v *NullableCreateTemplateFromPdfRequestDocumentsInner) Set(val *CreateTemplateFromPdfRequestDocumentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTemplateFromPdfRequestDocumentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTemplateFromPdfRequestDocumentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTemplateFromPdfRequestDocumentsInner(val *CreateTemplateFromPdfRequestDocumentsInner) *NullableCreateTemplateFromPdfRequestDocumentsInner {
	return &NullableCreateTemplateFromPdfRequestDocumentsInner{value: val, isSet: true}
}

func (v NullableCreateTemplateFromPdfRequestDocumentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTemplateFromPdfRequestDocumentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
