/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the CreateSubmissionResponseInnerPreferences type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionResponseInnerPreferences{}

// CreateSubmissionResponseInnerPreferences Submitter preferences.
type CreateSubmissionResponseInnerPreferences struct {
	// Indicates whether the signature request email should be sent.
	SendEmail *bool `json:"send_email,omitempty"`
	// Indicates whether the signature request should be sent via SMS.
	SendSms *bool `json:"send_sms,omitempty"`
}

// NewCreateSubmissionResponseInnerPreferences instantiates a new CreateSubmissionResponseInnerPreferences object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionResponseInnerPreferences() *CreateSubmissionResponseInnerPreferences {
	this := CreateSubmissionResponseInnerPreferences{}
	return &this
}

// NewCreateSubmissionResponseInnerPreferencesWithDefaults instantiates a new CreateSubmissionResponseInnerPreferences object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionResponseInnerPreferencesWithDefaults() *CreateSubmissionResponseInnerPreferences {
	this := CreateSubmissionResponseInnerPreferences{}
	return &this
}

// GetSendEmail returns the SendEmail field value if set, zero value otherwise.
func (o *CreateSubmissionResponseInnerPreferences) GetSendEmail() bool {
	if o == nil || IsNil(o.SendEmail) {
		var ret bool
		return ret
	}
	return *o.SendEmail
}

// GetSendEmailOk returns a tuple with the SendEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionResponseInnerPreferences) GetSendEmailOk() (*bool, bool) {
	if o == nil || IsNil(o.SendEmail) {
		return nil, false
	}
	return o.SendEmail, true
}

// HasSendEmail returns a boolean if a field has been set.
func (o *CreateSubmissionResponseInnerPreferences) HasSendEmail() bool {
	if o != nil && !IsNil(o.SendEmail) {
		return true
	}

	return false
}

// SetSendEmail gets a reference to the given bool and assigns it to the SendEmail field.
func (o *CreateSubmissionResponseInnerPreferences) SetSendEmail(v bool) {
	o.SendEmail = &v
}

// GetSendSms returns the SendSms field value if set, zero value otherwise.
func (o *CreateSubmissionResponseInnerPreferences) GetSendSms() bool {
	if o == nil || IsNil(o.SendSms) {
		var ret bool
		return ret
	}
	return *o.SendSms
}

// GetSendSmsOk returns a tuple with the SendSms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionResponseInnerPreferences) GetSendSmsOk() (*bool, bool) {
	if o == nil || IsNil(o.SendSms) {
		return nil, false
	}
	return o.SendSms, true
}

// HasSendSms returns a boolean if a field has been set.
func (o *CreateSubmissionResponseInnerPreferences) HasSendSms() bool {
	if o != nil && !IsNil(o.SendSms) {
		return true
	}

	return false
}

// SetSendSms gets a reference to the given bool and assigns it to the SendSms field.
func (o *CreateSubmissionResponseInnerPreferences) SetSendSms(v bool) {
	o.SendSms = &v
}

func (o CreateSubmissionResponseInnerPreferences) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionResponseInnerPreferences) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SendEmail) {
		toSerialize["send_email"] = o.SendEmail
	}
	if !IsNil(o.SendSms) {
		toSerialize["send_sms"] = o.SendSms
	}
	return toSerialize, nil
}

type NullableCreateSubmissionResponseInnerPreferences struct {
	value *CreateSubmissionResponseInnerPreferences
	isSet bool
}

func (v NullableCreateSubmissionResponseInnerPreferences) Get() *CreateSubmissionResponseInnerPreferences {
	return v.value
}

func (v *NullableCreateSubmissionResponseInnerPreferences) Set(val *CreateSubmissionResponseInnerPreferences) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionResponseInnerPreferences) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionResponseInnerPreferences) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionResponseInnerPreferences(val *CreateSubmissionResponseInnerPreferences) *NullableCreateSubmissionResponseInnerPreferences {
	return &NullableCreateSubmissionResponseInnerPreferences{value: val, isSet: true}
}

func (v NullableCreateSubmissionResponseInnerPreferences) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionResponseInnerPreferences) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
