/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner{}

// CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner struct for CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner
type CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner struct {
	// X-coordinate of the field area.
	X *float32 `json:"x,omitempty"`
	// Y-coordinate of the field area.
	Y *float32 `json:"y,omitempty"`
	// Width of the field area.
	W *float32 `json:"w,omitempty"`
	// Height of the field area.
	H *float32 `json:"h,omitempty"`
	// Page number of the field area. Starts from 1.
	Page *int32 `json:"page,omitempty"`
	// Option string value for 'radio' and 'multiple' select field types.
	Option *string `json:"option,omitempty"`
}

// NewCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner instantiates a new CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner() *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner {
	this := CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner{}
	return &this
}

// NewCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInnerWithDefaults instantiates a new CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInnerWithDefaults() *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner {
	this := CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner{}
	return &this
}

// GetX returns the X field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetX() float32 {
	if o == nil || IsNil(o.X) {
		var ret float32
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetXOk() (*float32, bool) {
	if o == nil || IsNil(o.X) {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) HasX() bool {
	if o != nil && !IsNil(o.X) {
		return true
	}

	return false
}

// SetX gets a reference to the given float32 and assigns it to the X field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) SetX(v float32) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetY() float32 {
	if o == nil || IsNil(o.Y) {
		var ret float32
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetYOk() (*float32, bool) {
	if o == nil || IsNil(o.Y) {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) HasY() bool {
	if o != nil && !IsNil(o.Y) {
		return true
	}

	return false
}

// SetY gets a reference to the given float32 and assigns it to the Y field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) SetY(v float32) {
	o.Y = &v
}

// GetW returns the W field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetW() float32 {
	if o == nil || IsNil(o.W) {
		var ret float32
		return ret
	}
	return *o.W
}

// GetWOk returns a tuple with the W field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetWOk() (*float32, bool) {
	if o == nil || IsNil(o.W) {
		return nil, false
	}
	return o.W, true
}

// HasW returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) HasW() bool {
	if o != nil && !IsNil(o.W) {
		return true
	}

	return false
}

// SetW gets a reference to the given float32 and assigns it to the W field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) SetW(v float32) {
	o.W = &v
}

// GetH returns the H field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetH() float32 {
	if o == nil || IsNil(o.H) {
		var ret float32
		return ret
	}
	return *o.H
}

// GetHOk returns a tuple with the H field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetHOk() (*float32, bool) {
	if o == nil || IsNil(o.H) {
		return nil, false
	}
	return o.H, true
}

// HasH returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) HasH() bool {
	if o != nil && !IsNil(o.H) {
		return true
	}

	return false
}

// SetH gets a reference to the given float32 and assigns it to the H field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) SetH(v float32) {
	o.H = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) SetPage(v int32) {
	o.Page = &v
}

// GetOption returns the Option field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetOption() string {
	if o == nil || IsNil(o.Option) {
		var ret string
		return ret
	}
	return *o.Option
}

// GetOptionOk returns a tuple with the Option field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) GetOptionOk() (*string, bool) {
	if o == nil || IsNil(o.Option) {
		return nil, false
	}
	return o.Option, true
}

// HasOption returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) HasOption() bool {
	if o != nil && !IsNil(o.Option) {
		return true
	}

	return false
}

// SetOption gets a reference to the given string and assigns it to the Option field.
func (o *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) SetOption(v string) {
	o.Option = &v
}

func (o CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.X) {
		toSerialize["x"] = o.X
	}
	if !IsNil(o.Y) {
		toSerialize["y"] = o.Y
	}
	if !IsNil(o.W) {
		toSerialize["w"] = o.W
	}
	if !IsNil(o.H) {
		toSerialize["h"] = o.H
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Option) {
		toSerialize["option"] = o.Option
	}
	return toSerialize, nil
}

type NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner struct {
	value *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner
	isSet bool
}

func (v NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) Get() *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner {
	return v.value
}

func (v *NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) Set(val *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner(val *CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) *NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner {
	return &NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner{value: val, isSet: true}
}

func (v NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
