/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the CreateSubmissionRequestMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionRequestMessage{}

// CreateSubmissionRequestMessage Custom signature request email message.
type CreateSubmissionRequestMessage struct {
	// Custom signature request email subject.
	Subject *string `json:"subject,omitempty"`
	// Custom signature request email body. Can include the following variables: {{template.name}}, {{submitter.link}}, {{account.name}}.
	Body *string `json:"body,omitempty"`
}

// NewCreateSubmissionRequestMessage instantiates a new CreateSubmissionRequestMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionRequestMessage() *CreateSubmissionRequestMessage {
	this := CreateSubmissionRequestMessage{}
	return &this
}

// NewCreateSubmissionRequestMessageWithDefaults instantiates a new CreateSubmissionRequestMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionRequestMessageWithDefaults() *CreateSubmissionRequestMessage {
	this := CreateSubmissionRequestMessage{}
	return &this
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *CreateSubmissionRequestMessage) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestMessage) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *CreateSubmissionRequestMessage) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *CreateSubmissionRequestMessage) SetSubject(v string) {
	o.Subject = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *CreateSubmissionRequestMessage) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionRequestMessage) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *CreateSubmissionRequestMessage) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *CreateSubmissionRequestMessage) SetBody(v string) {
	o.Body = &v
}

func (o CreateSubmissionRequestMessage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionRequestMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	return toSerialize, nil
}

type NullableCreateSubmissionRequestMessage struct {
	value *CreateSubmissionRequestMessage
	isSet bool
}

func (v NullableCreateSubmissionRequestMessage) Get() *CreateSubmissionRequestMessage {
	return v.value
}

func (v *NullableCreateSubmissionRequestMessage) Set(val *CreateSubmissionRequestMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionRequestMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionRequestMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionRequestMessage(val *CreateSubmissionRequestMessage) *NullableCreateSubmissionRequestMessage {
	return &NullableCreateSubmissionRequestMessage{value: val, isSet: true}
}

func (v NullableCreateSubmissionRequestMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionRequestMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
