/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateSubmissionFromPdfRequestDocumentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionFromPdfRequestDocumentsInner{}

// CreateSubmissionFromPdfRequestDocumentsInner struct for CreateSubmissionFromPdfRequestDocumentsInner
type CreateSubmissionFromPdfRequestDocumentsInner struct {
	// Name of the document.
	Name string `json:"name"`
	// Base64-encoded content of the PDF file or downloadable file URL.
	File string `json:"file"`
	// Fields are optional if you use {{...}} text tags to define fields in the document.
	Fields []CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner `json:"fields,omitempty"`
	// Document position in the submission. If not specified, the document will be added in the order it appears in the documents array.
	Position *int32 `json:"position,omitempty"`
}

type _CreateSubmissionFromPdfRequestDocumentsInner CreateSubmissionFromPdfRequestDocumentsInner

// NewCreateSubmissionFromPdfRequestDocumentsInner instantiates a new CreateSubmissionFromPdfRequestDocumentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionFromPdfRequestDocumentsInner(name string, file string) *CreateSubmissionFromPdfRequestDocumentsInner {
	this := CreateSubmissionFromPdfRequestDocumentsInner{}
	this.Name = name
	this.File = file
	return &this
}

// NewCreateSubmissionFromPdfRequestDocumentsInnerWithDefaults instantiates a new CreateSubmissionFromPdfRequestDocumentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionFromPdfRequestDocumentsInnerWithDefaults() *CreateSubmissionFromPdfRequestDocumentsInner {
	this := CreateSubmissionFromPdfRequestDocumentsInner{}
	return &this
}

// GetName returns the Name field value
func (o *CreateSubmissionFromPdfRequestDocumentsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSubmissionFromPdfRequestDocumentsInner) SetName(v string) {
	o.Name = v
}

// GetFile returns the File field value
func (o *CreateSubmissionFromPdfRequestDocumentsInner) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInner) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *CreateSubmissionFromPdfRequestDocumentsInner) SetFile(v string) {
	o.File = v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequestDocumentsInner) GetFields() []CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner {
	if o == nil || IsNil(o.Fields) {
		var ret []CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInner) GetFieldsOk() ([]CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInner) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner and assigns it to the Fields field.
func (o *CreateSubmissionFromPdfRequestDocumentsInner) SetFields(v []CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) {
	o.Fields = v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequestDocumentsInner) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInner) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInner) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *CreateSubmissionFromPdfRequestDocumentsInner) SetPosition(v int32) {
	o.Position = &v
}

func (o CreateSubmissionFromPdfRequestDocumentsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionFromPdfRequestDocumentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["file"] = o.File
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

func (o *CreateSubmissionFromPdfRequestDocumentsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"file",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSubmissionFromPdfRequestDocumentsInner := _CreateSubmissionFromPdfRequestDocumentsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSubmissionFromPdfRequestDocumentsInner)

	if err != nil {
		return err
	}

	*o = CreateSubmissionFromPdfRequestDocumentsInner(varCreateSubmissionFromPdfRequestDocumentsInner)

	return err
}

type NullableCreateSubmissionFromPdfRequestDocumentsInner struct {
	value *CreateSubmissionFromPdfRequestDocumentsInner
	isSet bool
}

func (v NullableCreateSubmissionFromPdfRequestDocumentsInner) Get() *CreateSubmissionFromPdfRequestDocumentsInner {
	return v.value
}

func (v *NullableCreateSubmissionFromPdfRequestDocumentsInner) Set(val *CreateSubmissionFromPdfRequestDocumentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionFromPdfRequestDocumentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionFromPdfRequestDocumentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionFromPdfRequestDocumentsInner(val *CreateSubmissionFromPdfRequestDocumentsInner) *NullableCreateSubmissionFromPdfRequestDocumentsInner {
	return &NullableCreateSubmissionFromPdfRequestDocumentsInner{value: val, isSet: true}
}

func (v NullableCreateSubmissionFromPdfRequestDocumentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionFromPdfRequestDocumentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
