/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateSubmissionFromPdfRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionFromPdfRequest{}

// CreateSubmissionFromPdfRequest struct for CreateSubmissionFromPdfRequest
type CreateSubmissionFromPdfRequest struct {
	// Name of the document submission.
	Name *string `json:"name,omitempty"`
	// Set `false` to disable signature request emails sending.
	SendEmail *bool `json:"send_email,omitempty"`
	// Set `true` to send signature request via phone number and SMS.
	SendSms *bool `json:"send_sms,omitempty"`
	// Pass 'random' to send signature request emails to all parties right away. The order is 'preserved' by default so the second party will receive a signature request email only after the document is signed by the first party.
	Order *string `json:"order,omitempty"`
	// Specify URL to redirect to after the submission completion.
	CompletedRedirectUrl *string `json:"completed_redirect_url,omitempty"`
	// Specify BCC address to send signed documents to after the completion.
	BccCompleted *string `json:"bcc_completed,omitempty"`
	// Specify Reply-To address to use in the notification emails.
	ReplyTo *string `json:"reply_to,omitempty"`
	// Specify the expiration date and time after which the submission becomes unavailable for signature.
	ExpireAt *string `json:"expire_at,omitempty"`
	// An optional array of template IDs to use in the submission along with the provided documents. This can be used to create multi-document submissions when some of the required documents exist within templates.
	TemplateIds []int32 `json:"template_ids,omitempty"`
	// An array of PDF documents to create a submission.
	Documents []CreateSubmissionFromPdfRequestDocumentsInner `json:"documents"`
	// The list of submitters for the submission.
	Submitters []CreateSubmissionFromPdfRequestSubmittersInner `json:"submitters"`
	Message    *CreateSubmissionRequestMessage                 `json:"message,omitempty"`
	// Remove PDF form fields from the documents.
	Flatten *bool `json:"flatten,omitempty"`
	// Set `true` to merge the documents into a single PDF file.
	MergeDocuments *bool `json:"merge_documents,omitempty"`
	// Pass `false` to disable the removal of {{text}} tags from the PDF. This can be used along with transparent text tags for faster and more robust PDF processing.
	RemoveTags *bool `json:"remove_tags,omitempty"`
}

type _CreateSubmissionFromPdfRequest CreateSubmissionFromPdfRequest

// NewCreateSubmissionFromPdfRequest instantiates a new CreateSubmissionFromPdfRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionFromPdfRequest(documents []CreateSubmissionFromPdfRequestDocumentsInner, submitters []CreateSubmissionFromPdfRequestSubmittersInner) *CreateSubmissionFromPdfRequest {
	this := CreateSubmissionFromPdfRequest{}
	var sendEmail bool = true
	this.SendEmail = &sendEmail
	var sendSms bool = false
	this.SendSms = &sendSms
	var order string = "preserved"
	this.Order = &order
	this.Documents = documents
	this.Submitters = submitters
	var flatten bool = false
	this.Flatten = &flatten
	var mergeDocuments bool = false
	this.MergeDocuments = &mergeDocuments
	var removeTags bool = true
	this.RemoveTags = &removeTags
	return &this
}

// NewCreateSubmissionFromPdfRequestWithDefaults instantiates a new CreateSubmissionFromPdfRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionFromPdfRequestWithDefaults() *CreateSubmissionFromPdfRequest {
	this := CreateSubmissionFromPdfRequest{}
	var sendEmail bool = true
	this.SendEmail = &sendEmail
	var sendSms bool = false
	this.SendSms = &sendSms
	var order string = "preserved"
	this.Order = &order
	var flatten bool = false
	this.Flatten = &flatten
	var mergeDocuments bool = false
	this.MergeDocuments = &mergeDocuments
	var removeTags bool = true
	this.RemoveTags = &removeTags
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateSubmissionFromPdfRequest) SetName(v string) {
	o.Name = &v
}

// GetSendEmail returns the SendEmail field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetSendEmail() bool {
	if o == nil || IsNil(o.SendEmail) {
		var ret bool
		return ret
	}
	return *o.SendEmail
}

// GetSendEmailOk returns a tuple with the SendEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetSendEmailOk() (*bool, bool) {
	if o == nil || IsNil(o.SendEmail) {
		return nil, false
	}
	return o.SendEmail, true
}

// HasSendEmail returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasSendEmail() bool {
	if o != nil && !IsNil(o.SendEmail) {
		return true
	}

	return false
}

// SetSendEmail gets a reference to the given bool and assigns it to the SendEmail field.
func (o *CreateSubmissionFromPdfRequest) SetSendEmail(v bool) {
	o.SendEmail = &v
}

// GetSendSms returns the SendSms field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetSendSms() bool {
	if o == nil || IsNil(o.SendSms) {
		var ret bool
		return ret
	}
	return *o.SendSms
}

// GetSendSmsOk returns a tuple with the SendSms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetSendSmsOk() (*bool, bool) {
	if o == nil || IsNil(o.SendSms) {
		return nil, false
	}
	return o.SendSms, true
}

// HasSendSms returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasSendSms() bool {
	if o != nil && !IsNil(o.SendSms) {
		return true
	}

	return false
}

// SetSendSms gets a reference to the given bool and assigns it to the SendSms field.
func (o *CreateSubmissionFromPdfRequest) SetSendSms(v bool) {
	o.SendSms = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetOrder() string {
	if o == nil || IsNil(o.Order) {
		var ret string
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetOrderOk() (*string, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given string and assigns it to the Order field.
func (o *CreateSubmissionFromPdfRequest) SetOrder(v string) {
	o.Order = &v
}

// GetCompletedRedirectUrl returns the CompletedRedirectUrl field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetCompletedRedirectUrl() string {
	if o == nil || IsNil(o.CompletedRedirectUrl) {
		var ret string
		return ret
	}
	return *o.CompletedRedirectUrl
}

// GetCompletedRedirectUrlOk returns a tuple with the CompletedRedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetCompletedRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CompletedRedirectUrl) {
		return nil, false
	}
	return o.CompletedRedirectUrl, true
}

// HasCompletedRedirectUrl returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasCompletedRedirectUrl() bool {
	if o != nil && !IsNil(o.CompletedRedirectUrl) {
		return true
	}

	return false
}

// SetCompletedRedirectUrl gets a reference to the given string and assigns it to the CompletedRedirectUrl field.
func (o *CreateSubmissionFromPdfRequest) SetCompletedRedirectUrl(v string) {
	o.CompletedRedirectUrl = &v
}

// GetBccCompleted returns the BccCompleted field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetBccCompleted() string {
	if o == nil || IsNil(o.BccCompleted) {
		var ret string
		return ret
	}
	return *o.BccCompleted
}

// GetBccCompletedOk returns a tuple with the BccCompleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetBccCompletedOk() (*string, bool) {
	if o == nil || IsNil(o.BccCompleted) {
		return nil, false
	}
	return o.BccCompleted, true
}

// HasBccCompleted returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasBccCompleted() bool {
	if o != nil && !IsNil(o.BccCompleted) {
		return true
	}

	return false
}

// SetBccCompleted gets a reference to the given string and assigns it to the BccCompleted field.
func (o *CreateSubmissionFromPdfRequest) SetBccCompleted(v string) {
	o.BccCompleted = &v
}

// GetReplyTo returns the ReplyTo field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetReplyTo() string {
	if o == nil || IsNil(o.ReplyTo) {
		var ret string
		return ret
	}
	return *o.ReplyTo
}

// GetReplyToOk returns a tuple with the ReplyTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetReplyToOk() (*string, bool) {
	if o == nil || IsNil(o.ReplyTo) {
		return nil, false
	}
	return o.ReplyTo, true
}

// HasReplyTo returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasReplyTo() bool {
	if o != nil && !IsNil(o.ReplyTo) {
		return true
	}

	return false
}

// SetReplyTo gets a reference to the given string and assigns it to the ReplyTo field.
func (o *CreateSubmissionFromPdfRequest) SetReplyTo(v string) {
	o.ReplyTo = &v
}

// GetExpireAt returns the ExpireAt field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetExpireAt() string {
	if o == nil || IsNil(o.ExpireAt) {
		var ret string
		return ret
	}
	return *o.ExpireAt
}

// GetExpireAtOk returns a tuple with the ExpireAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetExpireAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpireAt) {
		return nil, false
	}
	return o.ExpireAt, true
}

// HasExpireAt returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasExpireAt() bool {
	if o != nil && !IsNil(o.ExpireAt) {
		return true
	}

	return false
}

// SetExpireAt gets a reference to the given string and assigns it to the ExpireAt field.
func (o *CreateSubmissionFromPdfRequest) SetExpireAt(v string) {
	o.ExpireAt = &v
}

// GetTemplateIds returns the TemplateIds field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetTemplateIds() []int32 {
	if o == nil || IsNil(o.TemplateIds) {
		var ret []int32
		return ret
	}
	return o.TemplateIds
}

// GetTemplateIdsOk returns a tuple with the TemplateIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetTemplateIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.TemplateIds) {
		return nil, false
	}
	return o.TemplateIds, true
}

// HasTemplateIds returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasTemplateIds() bool {
	if o != nil && !IsNil(o.TemplateIds) {
		return true
	}

	return false
}

// SetTemplateIds gets a reference to the given []int32 and assigns it to the TemplateIds field.
func (o *CreateSubmissionFromPdfRequest) SetTemplateIds(v []int32) {
	o.TemplateIds = v
}

// GetDocuments returns the Documents field value
func (o *CreateSubmissionFromPdfRequest) GetDocuments() []CreateSubmissionFromPdfRequestDocumentsInner {
	if o == nil {
		var ret []CreateSubmissionFromPdfRequestDocumentsInner
		return ret
	}

	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetDocumentsOk() ([]CreateSubmissionFromPdfRequestDocumentsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Documents, true
}

// SetDocuments sets field value
func (o *CreateSubmissionFromPdfRequest) SetDocuments(v []CreateSubmissionFromPdfRequestDocumentsInner) {
	o.Documents = v
}

// GetSubmitters returns the Submitters field value
func (o *CreateSubmissionFromPdfRequest) GetSubmitters() []CreateSubmissionFromPdfRequestSubmittersInner {
	if o == nil {
		var ret []CreateSubmissionFromPdfRequestSubmittersInner
		return ret
	}

	return o.Submitters
}

// GetSubmittersOk returns a tuple with the Submitters field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetSubmittersOk() ([]CreateSubmissionFromPdfRequestSubmittersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Submitters, true
}

// SetSubmitters sets field value
func (o *CreateSubmissionFromPdfRequest) SetSubmitters(v []CreateSubmissionFromPdfRequestSubmittersInner) {
	o.Submitters = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetMessage() CreateSubmissionRequestMessage {
	if o == nil || IsNil(o.Message) {
		var ret CreateSubmissionRequestMessage
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetMessageOk() (*CreateSubmissionRequestMessage, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given CreateSubmissionRequestMessage and assigns it to the Message field.
func (o *CreateSubmissionFromPdfRequest) SetMessage(v CreateSubmissionRequestMessage) {
	o.Message = &v
}

// GetFlatten returns the Flatten field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetFlatten() bool {
	if o == nil || IsNil(o.Flatten) {
		var ret bool
		return ret
	}
	return *o.Flatten
}

// GetFlattenOk returns a tuple with the Flatten field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetFlattenOk() (*bool, bool) {
	if o == nil || IsNil(o.Flatten) {
		return nil, false
	}
	return o.Flatten, true
}

// HasFlatten returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasFlatten() bool {
	if o != nil && !IsNil(o.Flatten) {
		return true
	}

	return false
}

// SetFlatten gets a reference to the given bool and assigns it to the Flatten field.
func (o *CreateSubmissionFromPdfRequest) SetFlatten(v bool) {
	o.Flatten = &v
}

// GetMergeDocuments returns the MergeDocuments field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetMergeDocuments() bool {
	if o == nil || IsNil(o.MergeDocuments) {
		var ret bool
		return ret
	}
	return *o.MergeDocuments
}

// GetMergeDocumentsOk returns a tuple with the MergeDocuments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetMergeDocumentsOk() (*bool, bool) {
	if o == nil || IsNil(o.MergeDocuments) {
		return nil, false
	}
	return o.MergeDocuments, true
}

// HasMergeDocuments returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasMergeDocuments() bool {
	if o != nil && !IsNil(o.MergeDocuments) {
		return true
	}

	return false
}

// SetMergeDocuments gets a reference to the given bool and assigns it to the MergeDocuments field.
func (o *CreateSubmissionFromPdfRequest) SetMergeDocuments(v bool) {
	o.MergeDocuments = &v
}

// GetRemoveTags returns the RemoveTags field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequest) GetRemoveTags() bool {
	if o == nil || IsNil(o.RemoveTags) {
		var ret bool
		return ret
	}
	return *o.RemoveTags
}

// GetRemoveTagsOk returns a tuple with the RemoveTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequest) GetRemoveTagsOk() (*bool, bool) {
	if o == nil || IsNil(o.RemoveTags) {
		return nil, false
	}
	return o.RemoveTags, true
}

// HasRemoveTags returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequest) HasRemoveTags() bool {
	if o != nil && !IsNil(o.RemoveTags) {
		return true
	}

	return false
}

// SetRemoveTags gets a reference to the given bool and assigns it to the RemoveTags field.
func (o *CreateSubmissionFromPdfRequest) SetRemoveTags(v bool) {
	o.RemoveTags = &v
}

func (o CreateSubmissionFromPdfRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionFromPdfRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SendEmail) {
		toSerialize["send_email"] = o.SendEmail
	}
	if !IsNil(o.SendSms) {
		toSerialize["send_sms"] = o.SendSms
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.CompletedRedirectUrl) {
		toSerialize["completed_redirect_url"] = o.CompletedRedirectUrl
	}
	if !IsNil(o.BccCompleted) {
		toSerialize["bcc_completed"] = o.BccCompleted
	}
	if !IsNil(o.ReplyTo) {
		toSerialize["reply_to"] = o.ReplyTo
	}
	if !IsNil(o.ExpireAt) {
		toSerialize["expire_at"] = o.ExpireAt
	}
	if !IsNil(o.TemplateIds) {
		toSerialize["template_ids"] = o.TemplateIds
	}
	toSerialize["documents"] = o.Documents
	toSerialize["submitters"] = o.Submitters
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Flatten) {
		toSerialize["flatten"] = o.Flatten
	}
	if !IsNil(o.MergeDocuments) {
		toSerialize["merge_documents"] = o.MergeDocuments
	}
	if !IsNil(o.RemoveTags) {
		toSerialize["remove_tags"] = o.RemoveTags
	}
	return toSerialize, nil
}

func (o *CreateSubmissionFromPdfRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"documents",
		"submitters",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSubmissionFromPdfRequest := _CreateSubmissionFromPdfRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSubmissionFromPdfRequest)

	if err != nil {
		return err
	}

	*o = CreateSubmissionFromPdfRequest(varCreateSubmissionFromPdfRequest)

	return err
}

type NullableCreateSubmissionFromPdfRequest struct {
	value *CreateSubmissionFromPdfRequest
	isSet bool
}

func (v NullableCreateSubmissionFromPdfRequest) Get() *CreateSubmissionFromPdfRequest {
	return v.value
}

func (v *NullableCreateSubmissionFromPdfRequest) Set(val *CreateSubmissionFromPdfRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionFromPdfRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionFromPdfRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionFromPdfRequest(val *CreateSubmissionFromPdfRequest) *NullableCreateSubmissionFromPdfRequest {
	return &NullableCreateSubmissionFromPdfRequest{value: val, isSet: true}
}

func (v NullableCreateSubmissionFromPdfRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionFromPdfRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
