/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateSubmissionFromPdfResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionFromPdfResponse{}

// CreateSubmissionFromPdfResponse struct for CreateSubmissionFromPdfResponse
type CreateSubmissionFromPdfResponse struct {
	// Submission unique ID number.
	Id int32 `json:"id"`
	// Submission name.
	Name *string `json:"name,omitempty"`
	// The list of submitters.
	Submitters []CreateSubmissionFromPdfResponseSubmittersInner `json:"submitters"`
	// The source of the submission.
	Source string `json:"source"`
	// The order of submitters.
	SubmittersOrder string `json:"submitters_order"`
	// The status of the submission.
	Status string `json:"status"`
	// The one-off submission document files.
	Schema []CreateSubmissionFromPdfResponseSchemaInner `json:"schema,omitempty"`
	// List of fields to be filled in the one-off submission.
	Fields []GetTemplatesResponseDataInnerFieldsInner `json:"fields,omitempty"`
	// Specify the expiration date and time after which the submission becomes unavailable for signature.
	ExpireAt string `json:"expire_at"`
	// The date and time when the submission was created.
	CreatedAt string `json:"created_at"`
}

type _CreateSubmissionFromPdfResponse CreateSubmissionFromPdfResponse

// NewCreateSubmissionFromPdfResponse instantiates a new CreateSubmissionFromPdfResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionFromPdfResponse(id int32, submitters []CreateSubmissionFromPdfResponseSubmittersInner, source string, submittersOrder string, status string, expireAt string, createdAt string) *CreateSubmissionFromPdfResponse {
	this := CreateSubmissionFromPdfResponse{}
	this.Id = id
	this.Submitters = submitters
	this.Source = source
	this.SubmittersOrder = submittersOrder
	this.Status = status
	this.ExpireAt = expireAt
	this.CreatedAt = createdAt
	return &this
}

// NewCreateSubmissionFromPdfResponseWithDefaults instantiates a new CreateSubmissionFromPdfResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionFromPdfResponseWithDefaults() *CreateSubmissionFromPdfResponse {
	this := CreateSubmissionFromPdfResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateSubmissionFromPdfResponse) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfResponse) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateSubmissionFromPdfResponse) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateSubmissionFromPdfResponse) SetName(v string) {
	o.Name = &v
}

// GetSubmitters returns the Submitters field value
func (o *CreateSubmissionFromPdfResponse) GetSubmitters() []CreateSubmissionFromPdfResponseSubmittersInner {
	if o == nil {
		var ret []CreateSubmissionFromPdfResponseSubmittersInner
		return ret
	}

	return o.Submitters
}

// GetSubmittersOk returns a tuple with the Submitters field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfResponse) GetSubmittersOk() ([]CreateSubmissionFromPdfResponseSubmittersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Submitters, true
}

// SetSubmitters sets field value
func (o *CreateSubmissionFromPdfResponse) SetSubmitters(v []CreateSubmissionFromPdfResponseSubmittersInner) {
	o.Submitters = v
}

// GetSource returns the Source field value
func (o *CreateSubmissionFromPdfResponse) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfResponse) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *CreateSubmissionFromPdfResponse) SetSource(v string) {
	o.Source = v
}

// GetSubmittersOrder returns the SubmittersOrder field value
func (o *CreateSubmissionFromPdfResponse) GetSubmittersOrder() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubmittersOrder
}

// GetSubmittersOrderOk returns a tuple with the SubmittersOrder field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfResponse) GetSubmittersOrderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubmittersOrder, true
}

// SetSubmittersOrder sets field value
func (o *CreateSubmissionFromPdfResponse) SetSubmittersOrder(v string) {
	o.SubmittersOrder = v
}

// GetStatus returns the Status field value
func (o *CreateSubmissionFromPdfResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateSubmissionFromPdfResponse) SetStatus(v string) {
	o.Status = v
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfResponse) GetSchema() []CreateSubmissionFromPdfResponseSchemaInner {
	if o == nil || IsNil(o.Schema) {
		var ret []CreateSubmissionFromPdfResponseSchemaInner
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfResponse) GetSchemaOk() ([]CreateSubmissionFromPdfResponseSchemaInner, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfResponse) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given []CreateSubmissionFromPdfResponseSchemaInner and assigns it to the Schema field.
func (o *CreateSubmissionFromPdfResponse) SetSchema(v []CreateSubmissionFromPdfResponseSchemaInner) {
	o.Schema = v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfResponse) GetFields() []GetTemplatesResponseDataInnerFieldsInner {
	if o == nil || IsNil(o.Fields) {
		var ret []GetTemplatesResponseDataInnerFieldsInner
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfResponse) GetFieldsOk() ([]GetTemplatesResponseDataInnerFieldsInner, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfResponse) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []GetTemplatesResponseDataInnerFieldsInner and assigns it to the Fields field.
func (o *CreateSubmissionFromPdfResponse) SetFields(v []GetTemplatesResponseDataInnerFieldsInner) {
	o.Fields = v
}

// GetExpireAt returns the ExpireAt field value
func (o *CreateSubmissionFromPdfResponse) GetExpireAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpireAt
}

// GetExpireAtOk returns a tuple with the ExpireAt field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfResponse) GetExpireAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpireAt, true
}

// SetExpireAt sets field value
func (o *CreateSubmissionFromPdfResponse) SetExpireAt(v string) {
	o.ExpireAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CreateSubmissionFromPdfResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CreateSubmissionFromPdfResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o CreateSubmissionFromPdfResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionFromPdfResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["submitters"] = o.Submitters
	toSerialize["source"] = o.Source
	toSerialize["submitters_order"] = o.SubmittersOrder
	toSerialize["status"] = o.Status
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	toSerialize["expire_at"] = o.ExpireAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *CreateSubmissionFromPdfResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"submitters",
		"source",
		"submitters_order",
		"status",
		"expire_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSubmissionFromPdfResponse := _CreateSubmissionFromPdfResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSubmissionFromPdfResponse)

	if err != nil {
		return err
	}

	*o = CreateSubmissionFromPdfResponse(varCreateSubmissionFromPdfResponse)

	return err
}

type NullableCreateSubmissionFromPdfResponse struct {
	value *CreateSubmissionFromPdfResponse
	isSet bool
}

func (v NullableCreateSubmissionFromPdfResponse) Get() *CreateSubmissionFromPdfResponse {
	return v.value
}

func (v *NullableCreateSubmissionFromPdfResponse) Set(val *CreateSubmissionFromPdfResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionFromPdfResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionFromPdfResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionFromPdfResponse(val *CreateSubmissionFromPdfResponse) *NullableCreateSubmissionFromPdfResponse {
	return &NullableCreateSubmissionFromPdfResponse{value: val, isSet: true}
}

func (v NullableCreateSubmissionFromPdfResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionFromPdfResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
