/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner{}

// CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner struct for CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner
type CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner struct {
	// Name of the field.
	Name *string `json:"name,omitempty"`
	// Type of the field (e.g., text, signature, date, initials).
	Type *string `json:"type,omitempty"`
	// Role name of the signer.
	Role *string `json:"role,omitempty"`
	// Indicates if the field is required.
	Required *bool `json:"required,omitempty"`
	// Field title displayed to the user instead of the name, shown on the signing form. Supports Markdown.
	Title *string `json:"title,omitempty"`
	// Field description displayed on the signing form. Supports Markdown.
	Description *string `json:"description,omitempty"`
	// List of areas where the field is located in the document.
	Areas []CreateSubmissionFromPdfRequestDocumentsInnerFieldsInnerAreasInner `json:"areas,omitempty"`
	// An array of option values for 'select' field type.
	Options []string `json:"options,omitempty"`
}

// NewCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner instantiates a new CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner() *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner {
	this := CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner{}
	return &this
}

// NewCreateSubmissionFromPdfRequestDocumentsInnerFieldsInnerWithDefaults instantiates a new CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSubmissionFromPdfRequestDocumentsInnerFieldsInnerWithDefaults() *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner {
	this := CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) SetType(v string) {
	o.Type = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) SetRole(v string) {
	o.Role = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) SetRequired(v bool) {
	o.Required = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) SetDescription(v string) {
	o.Description = &v
}

// GetAreas returns the Areas field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetAreas() []CreateSubmissionFromPdfRequestDocumentsInnerFieldsInnerAreasInner {
	if o == nil || IsNil(o.Areas) {
		var ret []CreateSubmissionFromPdfRequestDocumentsInnerFieldsInnerAreasInner
		return ret
	}
	return o.Areas
}

// GetAreasOk returns a tuple with the Areas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetAreasOk() ([]CreateSubmissionFromPdfRequestDocumentsInnerFieldsInnerAreasInner, bool) {
	if o == nil || IsNil(o.Areas) {
		return nil, false
	}
	return o.Areas, true
}

// HasAreas returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) HasAreas() bool {
	if o != nil && !IsNil(o.Areas) {
		return true
	}

	return false
}

// SetAreas gets a reference to the given []CreateSubmissionFromPdfRequestDocumentsInnerFieldsInnerAreasInner and assigns it to the Areas field.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) SetAreas(v []CreateSubmissionFromPdfRequestDocumentsInnerFieldsInnerAreasInner) {
	o.Areas = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetOptions() []string {
	if o == nil || IsNil(o.Options) {
		var ret []string
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) GetOptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []string and assigns it to the Options field.
func (o *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) SetOptions(v []string) {
	o.Options = v
}

func (o CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Areas) {
		toSerialize["areas"] = o.Areas
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner struct {
	value *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner
	isSet bool
}

func (v NullableCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) Get() *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner {
	return v.value
}

func (v *NullableCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) Set(val *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner(val *CreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) *NullableCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner {
	return &NullableCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner{value: val, isSet: true}
}

func (v NullableCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubmissionFromPdfRequestDocumentsInnerFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
