/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateTemplateFromDocxRequestDocumentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTemplateFromDocxRequestDocumentsInner{}

// CreateTemplateFromDocxRequestDocumentsInner struct for CreateTemplateFromDocxRequestDocumentsInner
type CreateTemplateFromDocxRequestDocumentsInner struct {
	// Name of the document.
	Name string `json:"name"`
	// Base64-encoded content of the DOCX file or downloadable file URL.
	File string `json:"file"`
	// Set to `true` to make the document dynamic. When enabled, the DOCX document content can be edited or use [[variables]] in the template editor.
	Dynamic *bool `json:"dynamic,omitempty"`
	// Fields are optional if you use {{...}} text tags to define fields in the document.
	Fields []CreateTemplateFromDocxRequestDocumentsInnerFieldsInner `json:"fields,omitempty"`
}

type _CreateTemplateFromDocxRequestDocumentsInner CreateTemplateFromDocxRequestDocumentsInner

// NewCreateTemplateFromDocxRequestDocumentsInner instantiates a new CreateTemplateFromDocxRequestDocumentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTemplateFromDocxRequestDocumentsInner(name string, file string) *CreateTemplateFromDocxRequestDocumentsInner {
	this := CreateTemplateFromDocxRequestDocumentsInner{}
	this.Name = name
	this.File = file
	var dynamic bool = false
	this.Dynamic = &dynamic
	return &this
}

// NewCreateTemplateFromDocxRequestDocumentsInnerWithDefaults instantiates a new CreateTemplateFromDocxRequestDocumentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTemplateFromDocxRequestDocumentsInnerWithDefaults() *CreateTemplateFromDocxRequestDocumentsInner {
	this := CreateTemplateFromDocxRequestDocumentsInner{}
	var dynamic bool = false
	this.Dynamic = &dynamic
	return &this
}

// GetName returns the Name field value
func (o *CreateTemplateFromDocxRequestDocumentsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTemplateFromDocxRequestDocumentsInner) SetName(v string) {
	o.Name = v
}

// GetFile returns the File field value
func (o *CreateTemplateFromDocxRequestDocumentsInner) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInner) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *CreateTemplateFromDocxRequestDocumentsInner) SetFile(v string) {
	o.File = v
}

// GetDynamic returns the Dynamic field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInner) GetDynamic() bool {
	if o == nil || IsNil(o.Dynamic) {
		var ret bool
		return ret
	}
	return *o.Dynamic
}

// GetDynamicOk returns a tuple with the Dynamic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInner) GetDynamicOk() (*bool, bool) {
	if o == nil || IsNil(o.Dynamic) {
		return nil, false
	}
	return o.Dynamic, true
}

// HasDynamic returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInner) HasDynamic() bool {
	if o != nil && !IsNil(o.Dynamic) {
		return true
	}

	return false
}

// SetDynamic gets a reference to the given bool and assigns it to the Dynamic field.
func (o *CreateTemplateFromDocxRequestDocumentsInner) SetDynamic(v bool) {
	o.Dynamic = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *CreateTemplateFromDocxRequestDocumentsInner) GetFields() []CreateTemplateFromDocxRequestDocumentsInnerFieldsInner {
	if o == nil || IsNil(o.Fields) {
		var ret []CreateTemplateFromDocxRequestDocumentsInnerFieldsInner
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInner) GetFieldsOk() ([]CreateTemplateFromDocxRequestDocumentsInnerFieldsInner, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *CreateTemplateFromDocxRequestDocumentsInner) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []CreateTemplateFromDocxRequestDocumentsInnerFieldsInner and assigns it to the Fields field.
func (o *CreateTemplateFromDocxRequestDocumentsInner) SetFields(v []CreateTemplateFromDocxRequestDocumentsInnerFieldsInner) {
	o.Fields = v
}

func (o CreateTemplateFromDocxRequestDocumentsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTemplateFromDocxRequestDocumentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["file"] = o.File
	if !IsNil(o.Dynamic) {
		toSerialize["dynamic"] = o.Dynamic
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	return toSerialize, nil
}

func (o *CreateTemplateFromDocxRequestDocumentsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"file",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTemplateFromDocxRequestDocumentsInner := _CreateTemplateFromDocxRequestDocumentsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTemplateFromDocxRequestDocumentsInner)

	if err != nil {
		return err
	}

	*o = CreateTemplateFromDocxRequestDocumentsInner(varCreateTemplateFromDocxRequestDocumentsInner)

	return err
}

type NullableCreateTemplateFromDocxRequestDocumentsInner struct {
	value *CreateTemplateFromDocxRequestDocumentsInner
	isSet bool
}

func (v NullableCreateTemplateFromDocxRequestDocumentsInner) Get() *CreateTemplateFromDocxRequestDocumentsInner {
	return v.value
}

func (v *NullableCreateTemplateFromDocxRequestDocumentsInner) Set(val *CreateTemplateFromDocxRequestDocumentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTemplateFromDocxRequestDocumentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTemplateFromDocxRequestDocumentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTemplateFromDocxRequestDocumentsInner(val *CreateTemplateFromDocxRequestDocumentsInner) *NullableCreateTemplateFromDocxRequestDocumentsInner {
	return &NullableCreateTemplateFromDocxRequestDocumentsInner{value: val, isSet: true}
}

func (v NullableCreateTemplateFromDocxRequestDocumentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTemplateFromDocxRequestDocumentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
