/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateTemplateFromHtmlRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTemplateFromHtmlRequest{}

// CreateTemplateFromHtmlRequest struct for CreateTemplateFromHtmlRequest
type CreateTemplateFromHtmlRequest struct {
	// HTML template with field tags.
	Html string `json:"html"`
	// HTML template of the header to be displayed on every page.
	HtmlHeader *string `json:"html_header,omitempty"`
	// HTML template of the footer to be displayed on every page.
	HtmlFooter *string `json:"html_footer,omitempty"`
	// Template name. Random uuid will be assigned when not specified.
	Name *string `json:"name,omitempty"`
	// Page size. Letter 8.5 x 11 will be assigned when not specified.
	Size *string `json:"size,omitempty"`
	// Your application-specific unique string key to identify this template within your app. Existing template with specified `external_id` will be updated with a new HTML.
	ExternalId *string `json:"external_id,omitempty"`
	// The folder's name in which the template should be created.
	FolderName *string `json:"folder_name,omitempty"`
	// Set to `true` to make the template available via a shared link. This will allow anyone with the link to create a submission from this template.
	SharedLink *bool `json:"shared_link,omitempty"`
	// The list of documents built from HTML. Can be used to create a template with multiple documents. Leave `documents` param empty when using a top-level `html` param for a template with a single document.
	Documents []CreateTemplateFromHtmlRequestDocumentsInner `json:"documents,omitempty"`
}

type _CreateTemplateFromHtmlRequest CreateTemplateFromHtmlRequest

// NewCreateTemplateFromHtmlRequest instantiates a new CreateTemplateFromHtmlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTemplateFromHtmlRequest(html string) *CreateTemplateFromHtmlRequest {
	this := CreateTemplateFromHtmlRequest{}
	this.Html = html
	var size string = "Letter"
	this.Size = &size
	var sharedLink bool = true
	this.SharedLink = &sharedLink
	return &this
}

// NewCreateTemplateFromHtmlRequestWithDefaults instantiates a new CreateTemplateFromHtmlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTemplateFromHtmlRequestWithDefaults() *CreateTemplateFromHtmlRequest {
	this := CreateTemplateFromHtmlRequest{}
	var size string = "Letter"
	this.Size = &size
	var sharedLink bool = true
	this.SharedLink = &sharedLink
	return &this
}

// GetHtml returns the Html field value
func (o *CreateTemplateFromHtmlRequest) GetHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Html
}

// GetHtmlOk returns a tuple with the Html field value
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromHtmlRequest) GetHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Html, true
}

// SetHtml sets field value
func (o *CreateTemplateFromHtmlRequest) SetHtml(v string) {
	o.Html = v
}

// GetHtmlHeader returns the HtmlHeader field value if set, zero value otherwise.
func (o *CreateTemplateFromHtmlRequest) GetHtmlHeader() string {
	if o == nil || IsNil(o.HtmlHeader) {
		var ret string
		return ret
	}
	return *o.HtmlHeader
}

// GetHtmlHeaderOk returns a tuple with the HtmlHeader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromHtmlRequest) GetHtmlHeaderOk() (*string, bool) {
	if o == nil || IsNil(o.HtmlHeader) {
		return nil, false
	}
	return o.HtmlHeader, true
}

// HasHtmlHeader returns a boolean if a field has been set.
func (o *CreateTemplateFromHtmlRequest) HasHtmlHeader() bool {
	if o != nil && !IsNil(o.HtmlHeader) {
		return true
	}

	return false
}

// SetHtmlHeader gets a reference to the given string and assigns it to the HtmlHeader field.
func (o *CreateTemplateFromHtmlRequest) SetHtmlHeader(v string) {
	o.HtmlHeader = &v
}

// GetHtmlFooter returns the HtmlFooter field value if set, zero value otherwise.
func (o *CreateTemplateFromHtmlRequest) GetHtmlFooter() string {
	if o == nil || IsNil(o.HtmlFooter) {
		var ret string
		return ret
	}
	return *o.HtmlFooter
}

// GetHtmlFooterOk returns a tuple with the HtmlFooter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromHtmlRequest) GetHtmlFooterOk() (*string, bool) {
	if o == nil || IsNil(o.HtmlFooter) {
		return nil, false
	}
	return o.HtmlFooter, true
}

// HasHtmlFooter returns a boolean if a field has been set.
func (o *CreateTemplateFromHtmlRequest) HasHtmlFooter() bool {
	if o != nil && !IsNil(o.HtmlFooter) {
		return true
	}

	return false
}

// SetHtmlFooter gets a reference to the given string and assigns it to the HtmlFooter field.
func (o *CreateTemplateFromHtmlRequest) SetHtmlFooter(v string) {
	o.HtmlFooter = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateTemplateFromHtmlRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromHtmlRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateTemplateFromHtmlRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateTemplateFromHtmlRequest) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *CreateTemplateFromHtmlRequest) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromHtmlRequest) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *CreateTemplateFromHtmlRequest) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *CreateTemplateFromHtmlRequest) SetSize(v string) {
	o.Size = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *CreateTemplateFromHtmlRequest) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromHtmlRequest) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *CreateTemplateFromHtmlRequest) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *CreateTemplateFromHtmlRequest) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetFolderName returns the FolderName field value if set, zero value otherwise.
func (o *CreateTemplateFromHtmlRequest) GetFolderName() string {
	if o == nil || IsNil(o.FolderName) {
		var ret string
		return ret
	}
	return *o.FolderName
}

// GetFolderNameOk returns a tuple with the FolderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromHtmlRequest) GetFolderNameOk() (*string, bool) {
	if o == nil || IsNil(o.FolderName) {
		return nil, false
	}
	return o.FolderName, true
}

// HasFolderName returns a boolean if a field has been set.
func (o *CreateTemplateFromHtmlRequest) HasFolderName() bool {
	if o != nil && !IsNil(o.FolderName) {
		return true
	}

	return false
}

// SetFolderName gets a reference to the given string and assigns it to the FolderName field.
func (o *CreateTemplateFromHtmlRequest) SetFolderName(v string) {
	o.FolderName = &v
}

// GetSharedLink returns the SharedLink field value if set, zero value otherwise.
func (o *CreateTemplateFromHtmlRequest) GetSharedLink() bool {
	if o == nil || IsNil(o.SharedLink) {
		var ret bool
		return ret
	}
	return *o.SharedLink
}

// GetSharedLinkOk returns a tuple with the SharedLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromHtmlRequest) GetSharedLinkOk() (*bool, bool) {
	if o == nil || IsNil(o.SharedLink) {
		return nil, false
	}
	return o.SharedLink, true
}

// HasSharedLink returns a boolean if a field has been set.
func (o *CreateTemplateFromHtmlRequest) HasSharedLink() bool {
	if o != nil && !IsNil(o.SharedLink) {
		return true
	}

	return false
}

// SetSharedLink gets a reference to the given bool and assigns it to the SharedLink field.
func (o *CreateTemplateFromHtmlRequest) SetSharedLink(v bool) {
	o.SharedLink = &v
}

// GetDocuments returns the Documents field value if set, zero value otherwise.
func (o *CreateTemplateFromHtmlRequest) GetDocuments() []CreateTemplateFromHtmlRequestDocumentsInner {
	if o == nil || IsNil(o.Documents) {
		var ret []CreateTemplateFromHtmlRequestDocumentsInner
		return ret
	}
	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemplateFromHtmlRequest) GetDocumentsOk() ([]CreateTemplateFromHtmlRequestDocumentsInner, bool) {
	if o == nil || IsNil(o.Documents) {
		return nil, false
	}
	return o.Documents, true
}

// HasDocuments returns a boolean if a field has been set.
func (o *CreateTemplateFromHtmlRequest) HasDocuments() bool {
	if o != nil && !IsNil(o.Documents) {
		return true
	}

	return false
}

// SetDocuments gets a reference to the given []CreateTemplateFromHtmlRequestDocumentsInner and assigns it to the Documents field.
func (o *CreateTemplateFromHtmlRequest) SetDocuments(v []CreateTemplateFromHtmlRequestDocumentsInner) {
	o.Documents = v
}

func (o CreateTemplateFromHtmlRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTemplateFromHtmlRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["html"] = o.Html
	if !IsNil(o.HtmlHeader) {
		toSerialize["html_header"] = o.HtmlHeader
	}
	if !IsNil(o.HtmlFooter) {
		toSerialize["html_footer"] = o.HtmlFooter
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !IsNil(o.FolderName) {
		toSerialize["folder_name"] = o.FolderName
	}
	if !IsNil(o.SharedLink) {
		toSerialize["shared_link"] = o.SharedLink
	}
	if !IsNil(o.Documents) {
		toSerialize["documents"] = o.Documents
	}
	return toSerialize, nil
}

func (o *CreateTemplateFromHtmlRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"html",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTemplateFromHtmlRequest := _CreateTemplateFromHtmlRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTemplateFromHtmlRequest)

	if err != nil {
		return err
	}

	*o = CreateTemplateFromHtmlRequest(varCreateTemplateFromHtmlRequest)

	return err
}

type NullableCreateTemplateFromHtmlRequest struct {
	value *CreateTemplateFromHtmlRequest
	isSet bool
}

func (v NullableCreateTemplateFromHtmlRequest) Get() *CreateTemplateFromHtmlRequest {
	return v.value
}

func (v *NullableCreateTemplateFromHtmlRequest) Set(val *CreateTemplateFromHtmlRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTemplateFromHtmlRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTemplateFromHtmlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTemplateFromHtmlRequest(val *CreateTemplateFromHtmlRequest) *NullableCreateTemplateFromHtmlRequest {
	return &NullableCreateTemplateFromHtmlRequest{value: val, isSet: true}
}

func (v NullableCreateTemplateFromHtmlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTemplateFromHtmlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
