/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the FormWebhookRequestDataValuesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FormWebhookRequestDataValuesInner{}

// FormWebhookRequestDataValuesInner struct for FormWebhookRequestDataValuesInner
type FormWebhookRequestDataValuesInner struct {
	// The field name.
	Field *string `json:"field,omitempty"`
	// The field value.
	Value *string `json:"value,omitempty"`
}

// NewFormWebhookRequestDataValuesInner instantiates a new FormWebhookRequestDataValuesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFormWebhookRequestDataValuesInner() *FormWebhookRequestDataValuesInner {
	this := FormWebhookRequestDataValuesInner{}
	return &this
}

// NewFormWebhookRequestDataValuesInnerWithDefaults instantiates a new FormWebhookRequestDataValuesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormWebhookRequestDataValuesInnerWithDefaults() *FormWebhookRequestDataValuesInner {
	this := FormWebhookRequestDataValuesInner{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *FormWebhookRequestDataValuesInner) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormWebhookRequestDataValuesInner) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *FormWebhookRequestDataValuesInner) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *FormWebhookRequestDataValuesInner) SetField(v string) {
	o.Field = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *FormWebhookRequestDataValuesInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormWebhookRequestDataValuesInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *FormWebhookRequestDataValuesInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *FormWebhookRequestDataValuesInner) SetValue(v string) {
	o.Value = &v
}

func (o FormWebhookRequestDataValuesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FormWebhookRequestDataValuesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableFormWebhookRequestDataValuesInner struct {
	value *FormWebhookRequestDataValuesInner
	isSet bool
}

func (v NullableFormWebhookRequestDataValuesInner) Get() *FormWebhookRequestDataValuesInner {
	return v.value
}

func (v *NullableFormWebhookRequestDataValuesInner) Set(val *FormWebhookRequestDataValuesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFormWebhookRequestDataValuesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFormWebhookRequestDataValuesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFormWebhookRequestDataValuesInner(val *FormWebhookRequestDataValuesInner) *NullableFormWebhookRequestDataValuesInner {
	return &NullableFormWebhookRequestDataValuesInner{value: val, isSet: true}
}

func (v NullableFormWebhookRequestDataValuesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFormWebhookRequestDataValuesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
