/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"
)

// checks if the FormWebhookRequestDataTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FormWebhookRequestDataTemplate{}

// FormWebhookRequestDataTemplate Base template details.
type FormWebhookRequestDataTemplate struct {
	// The template's unique identifier.
	Id *float32 `json:"id,omitempty"`
	// The template's name.
	Name *string `json:"name,omitempty"`
	// Your application-specific unique string key to identify template within your app.
	ExternalId *string    `json:"external_id,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
	// Template folder name.
	FolderName *string `json:"folder_name,omitempty"`
}

// NewFormWebhookRequestDataTemplate instantiates a new FormWebhookRequestDataTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFormWebhookRequestDataTemplate() *FormWebhookRequestDataTemplate {
	this := FormWebhookRequestDataTemplate{}
	return &this
}

// NewFormWebhookRequestDataTemplateWithDefaults instantiates a new FormWebhookRequestDataTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormWebhookRequestDataTemplateWithDefaults() *FormWebhookRequestDataTemplate {
	this := FormWebhookRequestDataTemplate{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FormWebhookRequestDataTemplate) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormWebhookRequestDataTemplate) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FormWebhookRequestDataTemplate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *FormWebhookRequestDataTemplate) SetId(v float32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FormWebhookRequestDataTemplate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormWebhookRequestDataTemplate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FormWebhookRequestDataTemplate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FormWebhookRequestDataTemplate) SetName(v string) {
	o.Name = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *FormWebhookRequestDataTemplate) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormWebhookRequestDataTemplate) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *FormWebhookRequestDataTemplate) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *FormWebhookRequestDataTemplate) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FormWebhookRequestDataTemplate) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormWebhookRequestDataTemplate) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FormWebhookRequestDataTemplate) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FormWebhookRequestDataTemplate) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *FormWebhookRequestDataTemplate) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormWebhookRequestDataTemplate) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *FormWebhookRequestDataTemplate) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *FormWebhookRequestDataTemplate) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetFolderName returns the FolderName field value if set, zero value otherwise.
func (o *FormWebhookRequestDataTemplate) GetFolderName() string {
	if o == nil || IsNil(o.FolderName) {
		var ret string
		return ret
	}
	return *o.FolderName
}

// GetFolderNameOk returns a tuple with the FolderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormWebhookRequestDataTemplate) GetFolderNameOk() (*string, bool) {
	if o == nil || IsNil(o.FolderName) {
		return nil, false
	}
	return o.FolderName, true
}

// HasFolderName returns a boolean if a field has been set.
func (o *FormWebhookRequestDataTemplate) HasFolderName() bool {
	if o != nil && !IsNil(o.FolderName) {
		return true
	}

	return false
}

// SetFolderName gets a reference to the given string and assigns it to the FolderName field.
func (o *FormWebhookRequestDataTemplate) SetFolderName(v string) {
	o.FolderName = &v
}

func (o FormWebhookRequestDataTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FormWebhookRequestDataTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.FolderName) {
		toSerialize["folder_name"] = o.FolderName
	}
	return toSerialize, nil
}

type NullableFormWebhookRequestDataTemplate struct {
	value *FormWebhookRequestDataTemplate
	isSet bool
}

func (v NullableFormWebhookRequestDataTemplate) Get() *FormWebhookRequestDataTemplate {
	return v.value
}

func (v *NullableFormWebhookRequestDataTemplate) Set(val *FormWebhookRequestDataTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableFormWebhookRequestDataTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableFormWebhookRequestDataTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFormWebhookRequestDataTemplate(val *FormWebhookRequestDataTemplate) *NullableFormWebhookRequestDataTemplate {
	return &NullableFormWebhookRequestDataTemplate{value: val, isSet: true}
}

func (v NullableFormWebhookRequestDataTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFormWebhookRequestDataTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
