/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetTemplatesResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTemplatesResponseDataInner{}

// GetTemplatesResponseDataInner struct for GetTemplatesResponseDataInner
type GetTemplatesResponseDataInner struct {
	// Unique identifier of the document template.
	Id int32 `json:"id"`
	// Unique slug of the document template.
	Slug string `json:"slug"`
	// The name of the template.
	Name string `json:"name"`
	// Template preferences.
	Preferences map[string]interface{} `json:"preferences"`
	// List of documents attached to the template.
	Schema []GetTemplatesResponseDataInnerSchemaInner `json:"schema"`
	// List of fields to be filled in the template.
	Fields []GetTemplatesResponseDataInnerFieldsInner `json:"fields"`
	// The list of submitters for the template.
	Submitters []GetTemplatesResponseDataInnerSubmittersInner `json:"submitters"`
	// Unique identifier of the author of the template.
	AuthorId int32 `json:"author_id"`
	// Date and time when the template was archived.
	ArchivedAt NullableString `json:"archived_at,omitempty"`
	// The date and time when the template was created.
	CreatedAt string `json:"created_at"`
	// The date and time when the template was last updated.
	UpdatedAt string `json:"updated_at"`
	// Source of the template.
	Source string `json:"source"`
	// Your application-specific unique string key to identify this template within your app.
	ExternalId NullableString `json:"external_id"`
	// Unique identifier of the folder where the template is located.
	FolderId int32 `json:"folder_id"`
	// Folder name where the template is located.
	FolderName string `json:"folder_name"`
	// Indicates if the template is accessible by link.
	SharedLink *bool                               `json:"shared_link,omitempty"`
	Author     GetTemplatesResponseDataInnerAuthor `json:"author"`
	// List of documents attached to the template.
	Documents []GetTemplatesResponseDataInnerDocumentsInner `json:"documents"`
}

type _GetTemplatesResponseDataInner GetTemplatesResponseDataInner

// NewGetTemplatesResponseDataInner instantiates a new GetTemplatesResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTemplatesResponseDataInner(id int32, slug string, name string, preferences map[string]interface{}, schema []GetTemplatesResponseDataInnerSchemaInner, fields []GetTemplatesResponseDataInnerFieldsInner, submitters []GetTemplatesResponseDataInnerSubmittersInner, authorId int32, createdAt string, updatedAt string, source string, externalId NullableString, folderId int32, folderName string, author GetTemplatesResponseDataInnerAuthor, documents []GetTemplatesResponseDataInnerDocumentsInner) *GetTemplatesResponseDataInner {
	this := GetTemplatesResponseDataInner{}
	this.Id = id
	this.Slug = slug
	this.Name = name
	this.Preferences = preferences
	this.Schema = schema
	this.Fields = fields
	this.Submitters = submitters
	this.AuthorId = authorId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Source = source
	this.ExternalId = externalId
	this.FolderId = folderId
	this.FolderName = folderName
	this.Author = author
	this.Documents = documents
	return &this
}

// NewGetTemplatesResponseDataInnerWithDefaults instantiates a new GetTemplatesResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTemplatesResponseDataInnerWithDefaults() *GetTemplatesResponseDataInner {
	this := GetTemplatesResponseDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *GetTemplatesResponseDataInner) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetTemplatesResponseDataInner) SetId(v int32) {
	o.Id = v
}

// GetSlug returns the Slug field value
func (o *GetTemplatesResponseDataInner) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *GetTemplatesResponseDataInner) SetSlug(v string) {
	o.Slug = v
}

// GetName returns the Name field value
func (o *GetTemplatesResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetTemplatesResponseDataInner) SetName(v string) {
	o.Name = v
}

// GetPreferences returns the Preferences field value
func (o *GetTemplatesResponseDataInner) GetPreferences() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetPreferencesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Preferences, true
}

// SetPreferences sets field value
func (o *GetTemplatesResponseDataInner) SetPreferences(v map[string]interface{}) {
	o.Preferences = v
}

// GetSchema returns the Schema field value
func (o *GetTemplatesResponseDataInner) GetSchema() []GetTemplatesResponseDataInnerSchemaInner {
	if o == nil {
		var ret []GetTemplatesResponseDataInnerSchemaInner
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetSchemaOk() ([]GetTemplatesResponseDataInnerSchemaInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Schema, true
}

// SetSchema sets field value
func (o *GetTemplatesResponseDataInner) SetSchema(v []GetTemplatesResponseDataInnerSchemaInner) {
	o.Schema = v
}

// GetFields returns the Fields field value
func (o *GetTemplatesResponseDataInner) GetFields() []GetTemplatesResponseDataInnerFieldsInner {
	if o == nil {
		var ret []GetTemplatesResponseDataInnerFieldsInner
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetFieldsOk() ([]GetTemplatesResponseDataInnerFieldsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fields, true
}

// SetFields sets field value
func (o *GetTemplatesResponseDataInner) SetFields(v []GetTemplatesResponseDataInnerFieldsInner) {
	o.Fields = v
}

// GetSubmitters returns the Submitters field value
func (o *GetTemplatesResponseDataInner) GetSubmitters() []GetTemplatesResponseDataInnerSubmittersInner {
	if o == nil {
		var ret []GetTemplatesResponseDataInnerSubmittersInner
		return ret
	}

	return o.Submitters
}

// GetSubmittersOk returns a tuple with the Submitters field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetSubmittersOk() ([]GetTemplatesResponseDataInnerSubmittersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Submitters, true
}

// SetSubmitters sets field value
func (o *GetTemplatesResponseDataInner) SetSubmitters(v []GetTemplatesResponseDataInnerSubmittersInner) {
	o.Submitters = v
}

// GetAuthorId returns the AuthorId field value
func (o *GetTemplatesResponseDataInner) GetAuthorId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AuthorId
}

// GetAuthorIdOk returns a tuple with the AuthorId field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetAuthorIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorId, true
}

// SetAuthorId sets field value
func (o *GetTemplatesResponseDataInner) SetAuthorId(v int32) {
	o.AuthorId = v
}

// GetArchivedAt returns the ArchivedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetTemplatesResponseDataInner) GetArchivedAt() string {
	if o == nil || IsNil(o.ArchivedAt.Get()) {
		var ret string
		return ret
	}
	return *o.ArchivedAt.Get()
}

// GetArchivedAtOk returns a tuple with the ArchivedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetTemplatesResponseDataInner) GetArchivedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArchivedAt.Get(), o.ArchivedAt.IsSet()
}

// HasArchivedAt returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInner) HasArchivedAt() bool {
	if o != nil && o.ArchivedAt.IsSet() {
		return true
	}

	return false
}

// SetArchivedAt gets a reference to the given NullableString and assigns it to the ArchivedAt field.
func (o *GetTemplatesResponseDataInner) SetArchivedAt(v string) {
	o.ArchivedAt.Set(&v)
}

// SetArchivedAtNil sets the value for ArchivedAt to be an explicit nil
func (o *GetTemplatesResponseDataInner) SetArchivedAtNil() {
	o.ArchivedAt.Set(nil)
}

// UnsetArchivedAt ensures that no value is present for ArchivedAt, not even an explicit nil
func (o *GetTemplatesResponseDataInner) UnsetArchivedAt() {
	o.ArchivedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetTemplatesResponseDataInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetTemplatesResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetTemplatesResponseDataInner) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetTemplatesResponseDataInner) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetSource returns the Source field value
func (o *GetTemplatesResponseDataInner) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *GetTemplatesResponseDataInner) SetSource(v string) {
	o.Source = v
}

// GetExternalId returns the ExternalId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetTemplatesResponseDataInner) GetExternalId() string {
	if o == nil || o.ExternalId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetTemplatesResponseDataInner) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// SetExternalId sets field value
func (o *GetTemplatesResponseDataInner) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// GetFolderId returns the FolderId field value
func (o *GetTemplatesResponseDataInner) GetFolderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FolderId
}

// GetFolderIdOk returns a tuple with the FolderId field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetFolderIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FolderId, true
}

// SetFolderId sets field value
func (o *GetTemplatesResponseDataInner) SetFolderId(v int32) {
	o.FolderId = v
}

// GetFolderName returns the FolderName field value
func (o *GetTemplatesResponseDataInner) GetFolderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FolderName
}

// GetFolderNameOk returns a tuple with the FolderName field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetFolderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FolderName, true
}

// SetFolderName sets field value
func (o *GetTemplatesResponseDataInner) SetFolderName(v string) {
	o.FolderName = v
}

// GetSharedLink returns the SharedLink field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInner) GetSharedLink() bool {
	if o == nil || IsNil(o.SharedLink) {
		var ret bool
		return ret
	}
	return *o.SharedLink
}

// GetSharedLinkOk returns a tuple with the SharedLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetSharedLinkOk() (*bool, bool) {
	if o == nil || IsNil(o.SharedLink) {
		return nil, false
	}
	return o.SharedLink, true
}

// HasSharedLink returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInner) HasSharedLink() bool {
	if o != nil && !IsNil(o.SharedLink) {
		return true
	}

	return false
}

// SetSharedLink gets a reference to the given bool and assigns it to the SharedLink field.
func (o *GetTemplatesResponseDataInner) SetSharedLink(v bool) {
	o.SharedLink = &v
}

// GetAuthor returns the Author field value
func (o *GetTemplatesResponseDataInner) GetAuthor() GetTemplatesResponseDataInnerAuthor {
	if o == nil {
		var ret GetTemplatesResponseDataInnerAuthor
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetAuthorOk() (*GetTemplatesResponseDataInnerAuthor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *GetTemplatesResponseDataInner) SetAuthor(v GetTemplatesResponseDataInnerAuthor) {
	o.Author = v
}

// GetDocuments returns the Documents field value
func (o *GetTemplatesResponseDataInner) GetDocuments() []GetTemplatesResponseDataInnerDocumentsInner {
	if o == nil {
		var ret []GetTemplatesResponseDataInnerDocumentsInner
		return ret
	}

	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInner) GetDocumentsOk() ([]GetTemplatesResponseDataInnerDocumentsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Documents, true
}

// SetDocuments sets field value
func (o *GetTemplatesResponseDataInner) SetDocuments(v []GetTemplatesResponseDataInnerDocumentsInner) {
	o.Documents = v
}

func (o GetTemplatesResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTemplatesResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["slug"] = o.Slug
	toSerialize["name"] = o.Name
	toSerialize["preferences"] = o.Preferences
	toSerialize["schema"] = o.Schema
	toSerialize["fields"] = o.Fields
	toSerialize["submitters"] = o.Submitters
	toSerialize["author_id"] = o.AuthorId
	if o.ArchivedAt.IsSet() {
		toSerialize["archived_at"] = o.ArchivedAt.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["source"] = o.Source
	toSerialize["external_id"] = o.ExternalId.Get()
	toSerialize["folder_id"] = o.FolderId
	toSerialize["folder_name"] = o.FolderName
	if !IsNil(o.SharedLink) {
		toSerialize["shared_link"] = o.SharedLink
	}
	toSerialize["author"] = o.Author
	toSerialize["documents"] = o.Documents
	return toSerialize, nil
}

func (o *GetTemplatesResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"slug",
		"name",
		"preferences",
		"schema",
		"fields",
		"submitters",
		"author_id",
		"created_at",
		"updated_at",
		"source",
		"external_id",
		"folder_id",
		"folder_name",
		"author",
		"documents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetTemplatesResponseDataInner := _GetTemplatesResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetTemplatesResponseDataInner)

	if err != nil {
		return err
	}

	*o = GetTemplatesResponseDataInner(varGetTemplatesResponseDataInner)

	return err
}

type NullableGetTemplatesResponseDataInner struct {
	value *GetTemplatesResponseDataInner
	isSet bool
}

func (v NullableGetTemplatesResponseDataInner) Get() *GetTemplatesResponseDataInner {
	return v.value
}

func (v *NullableGetTemplatesResponseDataInner) Set(val *GetTemplatesResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTemplatesResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTemplatesResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTemplatesResponseDataInner(val *GetTemplatesResponseDataInner) *NullableGetTemplatesResponseDataInner {
	return &NullableGetTemplatesResponseDataInner{value: val, isSet: true}
}

func (v NullableGetTemplatesResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTemplatesResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
