/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the GetSubmitterResponseTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSubmitterResponseTemplate{}

// GetSubmitterResponseTemplate Base template details.
type GetSubmitterResponseTemplate struct {
	// Unique identifier of the document template.
	Id int32 `json:"id"`
	// The name of the template.
	Name string `json:"name"`
	// The date and time when the template was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time when the template was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

type _GetSubmitterResponseTemplate GetSubmitterResponseTemplate

// NewGetSubmitterResponseTemplate instantiates a new GetSubmitterResponseTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSubmitterResponseTemplate(id int32, name string, createdAt time.Time, updatedAt time.Time) *GetSubmitterResponseTemplate {
	this := GetSubmitterResponseTemplate{}
	this.Id = id
	this.Name = name
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGetSubmitterResponseTemplateWithDefaults instantiates a new GetSubmitterResponseTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSubmitterResponseTemplateWithDefaults() *GetSubmitterResponseTemplate {
	this := GetSubmitterResponseTemplate{}
	return &this
}

// GetId returns the Id field value
func (o *GetSubmitterResponseTemplate) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponseTemplate) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetSubmitterResponseTemplate) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetSubmitterResponseTemplate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponseTemplate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetSubmitterResponseTemplate) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetSubmitterResponseTemplate) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponseTemplate) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetSubmitterResponseTemplate) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetSubmitterResponseTemplate) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponseTemplate) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetSubmitterResponseTemplate) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o GetSubmitterResponseTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSubmitterResponseTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *GetSubmitterResponseTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSubmitterResponseTemplate := _GetSubmitterResponseTemplate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSubmitterResponseTemplate)

	if err != nil {
		return err
	}

	*o = GetSubmitterResponseTemplate(varGetSubmitterResponseTemplate)

	return err
}

type NullableGetSubmitterResponseTemplate struct {
	value *GetSubmitterResponseTemplate
	isSet bool
}

func (v NullableGetSubmitterResponseTemplate) Get() *GetSubmitterResponseTemplate {
	return v.value
}

func (v *NullableGetSubmitterResponseTemplate) Set(val *GetSubmitterResponseTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSubmitterResponseTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSubmitterResponseTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSubmitterResponseTemplate(val *GetSubmitterResponseTemplate) *NullableGetSubmitterResponseTemplate {
	return &NullableGetSubmitterResponseTemplate{value: val, isSet: true}
}

func (v NullableGetSubmitterResponseTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSubmitterResponseTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
