/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the GetTemplatesResponseDataInnerFieldsInnerPreferences type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTemplatesResponseDataInnerFieldsInnerPreferences{}

// GetTemplatesResponseDataInnerFieldsInnerPreferences Field display preferences.
type GetTemplatesResponseDataInnerFieldsInnerPreferences struct {
	// Font size of the field value in pixels.
	FontSize *int32 `json:"font_size,omitempty"`
	// Font type of the field value.
	FontType *string `json:"font_type,omitempty"`
	// Font family of the field value.
	Font *string `json:"font,omitempty"`
	// Font color of the field value.
	Color *string `json:"color,omitempty"`
	// Field box background color.
	Background *string `json:"background,omitempty"`
	// Horizontal alignment of the field text value.
	Align *string `json:"align,omitempty"`
	// Vertical alignment of the field text value.
	Valign *string `json:"valign,omitempty"`
	// The data format for different field types.
	Format *string `json:"format,omitempty"`
	// Price value of the payment field. Only for payment fields.
	Price *float32 `json:"price,omitempty"`
	// Currency value of the payment field. Only for payment fields.
	Currency *string `json:"currency,omitempty"`
	// Indicates if the field is masked on the document.
	Mask *bool `json:"mask,omitempty"`
	// An array of signature reasons to choose from.
	Reasons []string `json:"reasons,omitempty"`
}

// NewGetTemplatesResponseDataInnerFieldsInnerPreferences instantiates a new GetTemplatesResponseDataInnerFieldsInnerPreferences object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTemplatesResponseDataInnerFieldsInnerPreferences() *GetTemplatesResponseDataInnerFieldsInnerPreferences {
	this := GetTemplatesResponseDataInnerFieldsInnerPreferences{}
	return &this
}

// NewGetTemplatesResponseDataInnerFieldsInnerPreferencesWithDefaults instantiates a new GetTemplatesResponseDataInnerFieldsInnerPreferences object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTemplatesResponseDataInnerFieldsInnerPreferencesWithDefaults() *GetTemplatesResponseDataInnerFieldsInnerPreferences {
	this := GetTemplatesResponseDataInnerFieldsInnerPreferences{}
	return &this
}

// GetFontSize returns the FontSize field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetFontSize() int32 {
	if o == nil || IsNil(o.FontSize) {
		var ret int32
		return ret
	}
	return *o.FontSize
}

// GetFontSizeOk returns a tuple with the FontSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetFontSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.FontSize) {
		return nil, false
	}
	return o.FontSize, true
}

// HasFontSize returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasFontSize() bool {
	if o != nil && !IsNil(o.FontSize) {
		return true
	}

	return false
}

// SetFontSize gets a reference to the given int32 and assigns it to the FontSize field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetFontSize(v int32) {
	o.FontSize = &v
}

// GetFontType returns the FontType field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetFontType() string {
	if o == nil || IsNil(o.FontType) {
		var ret string
		return ret
	}
	return *o.FontType
}

// GetFontTypeOk returns a tuple with the FontType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetFontTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FontType) {
		return nil, false
	}
	return o.FontType, true
}

// HasFontType returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasFontType() bool {
	if o != nil && !IsNil(o.FontType) {
		return true
	}

	return false
}

// SetFontType gets a reference to the given string and assigns it to the FontType field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetFontType(v string) {
	o.FontType = &v
}

// GetFont returns the Font field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetFont() string {
	if o == nil || IsNil(o.Font) {
		var ret string
		return ret
	}
	return *o.Font
}

// GetFontOk returns a tuple with the Font field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetFontOk() (*string, bool) {
	if o == nil || IsNil(o.Font) {
		return nil, false
	}
	return o.Font, true
}

// HasFont returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasFont() bool {
	if o != nil && !IsNil(o.Font) {
		return true
	}

	return false
}

// SetFont gets a reference to the given string and assigns it to the Font field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetFont(v string) {
	o.Font = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetColor(v string) {
	o.Color = &v
}

// GetBackground returns the Background field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetBackground() string {
	if o == nil || IsNil(o.Background) {
		var ret string
		return ret
	}
	return *o.Background
}

// GetBackgroundOk returns a tuple with the Background field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetBackgroundOk() (*string, bool) {
	if o == nil || IsNil(o.Background) {
		return nil, false
	}
	return o.Background, true
}

// HasBackground returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasBackground() bool {
	if o != nil && !IsNil(o.Background) {
		return true
	}

	return false
}

// SetBackground gets a reference to the given string and assigns it to the Background field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetBackground(v string) {
	o.Background = &v
}

// GetAlign returns the Align field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetAlign() string {
	if o == nil || IsNil(o.Align) {
		var ret string
		return ret
	}
	return *o.Align
}

// GetAlignOk returns a tuple with the Align field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetAlignOk() (*string, bool) {
	if o == nil || IsNil(o.Align) {
		return nil, false
	}
	return o.Align, true
}

// HasAlign returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasAlign() bool {
	if o != nil && !IsNil(o.Align) {
		return true
	}

	return false
}

// SetAlign gets a reference to the given string and assigns it to the Align field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetAlign(v string) {
	o.Align = &v
}

// GetValign returns the Valign field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetValign() string {
	if o == nil || IsNil(o.Valign) {
		var ret string
		return ret
	}
	return *o.Valign
}

// GetValignOk returns a tuple with the Valign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetValignOk() (*string, bool) {
	if o == nil || IsNil(o.Valign) {
		return nil, false
	}
	return o.Valign, true
}

// HasValign returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasValign() bool {
	if o != nil && !IsNil(o.Valign) {
		return true
	}

	return false
}

// SetValign gets a reference to the given string and assigns it to the Valign field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetValign(v string) {
	o.Valign = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetFormat(v string) {
	o.Format = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetPrice(v float32) {
	o.Price = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetCurrency(v string) {
	o.Currency = &v
}

// GetMask returns the Mask field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetMask() bool {
	if o == nil || IsNil(o.Mask) {
		var ret bool
		return ret
	}
	return *o.Mask
}

// GetMaskOk returns a tuple with the Mask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetMaskOk() (*bool, bool) {
	if o == nil || IsNil(o.Mask) {
		return nil, false
	}
	return o.Mask, true
}

// HasMask returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasMask() bool {
	if o != nil && !IsNil(o.Mask) {
		return true
	}

	return false
}

// SetMask gets a reference to the given bool and assigns it to the Mask field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetMask(v bool) {
	o.Mask = &v
}

// GetReasons returns the Reasons field value if set, zero value otherwise.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetReasons() []string {
	if o == nil || IsNil(o.Reasons) {
		var ret []string
		return ret
	}
	return o.Reasons
}

// GetReasonsOk returns a tuple with the Reasons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) GetReasonsOk() ([]string, bool) {
	if o == nil || IsNil(o.Reasons) {
		return nil, false
	}
	return o.Reasons, true
}

// HasReasons returns a boolean if a field has been set.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) HasReasons() bool {
	if o != nil && !IsNil(o.Reasons) {
		return true
	}

	return false
}

// SetReasons gets a reference to the given []string and assigns it to the Reasons field.
func (o *GetTemplatesResponseDataInnerFieldsInnerPreferences) SetReasons(v []string) {
	o.Reasons = v
}

func (o GetTemplatesResponseDataInnerFieldsInnerPreferences) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTemplatesResponseDataInnerFieldsInnerPreferences) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FontSize) {
		toSerialize["font_size"] = o.FontSize
	}
	if !IsNil(o.FontType) {
		toSerialize["font_type"] = o.FontType
	}
	if !IsNil(o.Font) {
		toSerialize["font"] = o.Font
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Background) {
		toSerialize["background"] = o.Background
	}
	if !IsNil(o.Align) {
		toSerialize["align"] = o.Align
	}
	if !IsNil(o.Valign) {
		toSerialize["valign"] = o.Valign
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Mask) {
		toSerialize["mask"] = o.Mask
	}
	if !IsNil(o.Reasons) {
		toSerialize["reasons"] = o.Reasons
	}
	return toSerialize, nil
}

type NullableGetTemplatesResponseDataInnerFieldsInnerPreferences struct {
	value *GetTemplatesResponseDataInnerFieldsInnerPreferences
	isSet bool
}

func (v NullableGetTemplatesResponseDataInnerFieldsInnerPreferences) Get() *GetTemplatesResponseDataInnerFieldsInnerPreferences {
	return v.value
}

func (v *NullableGetTemplatesResponseDataInnerFieldsInnerPreferences) Set(val *GetTemplatesResponseDataInnerFieldsInnerPreferences) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTemplatesResponseDataInnerFieldsInnerPreferences) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTemplatesResponseDataInnerFieldsInnerPreferences) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTemplatesResponseDataInnerFieldsInnerPreferences(val *GetTemplatesResponseDataInnerFieldsInnerPreferences) *NullableGetTemplatesResponseDataInnerFieldsInnerPreferences {
	return &NullableGetTemplatesResponseDataInnerFieldsInnerPreferences{value: val, isSet: true}
}

func (v NullableGetTemplatesResponseDataInnerFieldsInnerPreferences) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTemplatesResponseDataInnerFieldsInnerPreferences) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
