/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetSubmitterResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSubmitterResponse{}

// GetSubmitterResponse struct for GetSubmitterResponse
type GetSubmitterResponse struct {
	// Submitter unique ID number.
	Id int32 `json:"id"`
	// Submission unique ID number.
	SubmissionId int32 `json:"submission_id"`
	// Submitter UUID.
	Uuid string `json:"uuid"`
	// The email address of the submitter.
	Email NullableString `json:"email"`
	// Unique key to be used in the form signing link and embedded form.
	Slug string `json:"slug"`
	// The date and time when the signing request was sent to the submitter.
	SentAt NullableString `json:"sent_at"`
	// The date and time when the submitter opened the signing form.
	OpenedAt NullableString `json:"opened_at"`
	// The date and time when the submitter completed the signing form.
	CompletedAt NullableString `json:"completed_at"`
	// The date and time when the submitter declined the signing form.
	DeclinedAt NullableString `json:"declined_at"`
	// The date and time when the submitter was created.
	CreatedAt string `json:"created_at"`
	// The date and time when the submitter was last updated.
	UpdatedAt string `json:"updated_at"`
	// The name of the submitter.
	Name NullableString `json:"name"`
	// The phone number of the submitter.
	Phone NullableString `json:"phone"`
	// The status of signing request for the submitter.
	Status string `json:"status"`
	// Your application-specific unique string key to identify this submitter within your app.
	ExternalId NullableString `json:"external_id"`
	// Metadata object with additional submitter information.
	Metadata map[string]interface{} `json:"metadata"`
	// Submitter preferences.
	Preferences map[string]interface{}       `json:"preferences"`
	Template    GetSubmitterResponseTemplate `json:"template"`
	// An array of events related to the submission.
	SubmissionEvents []GetSubmissionResponseSubmissionEventsInner `json:"submission_events"`
	// An array of pre-filled values for the submitter.
	Values []CreateSubmissionResponseInnerValuesInner `json:"values"`
	// An array of completed or signed documents by the submitter.
	Documents []GetSubmissionResponseSubmittersInnerDocumentsInner `json:"documents"`
	// The role of the submitter in the signing process.
	Role string `json:"role"`
}

type _GetSubmitterResponse GetSubmitterResponse

// NewGetSubmitterResponse instantiates a new GetSubmitterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSubmitterResponse(id int32, submissionId int32, uuid string, email NullableString, slug string, sentAt NullableString, openedAt NullableString, completedAt NullableString, declinedAt NullableString, createdAt string, updatedAt string, name NullableString, phone NullableString, status string, externalId NullableString, metadata map[string]interface{}, preferences map[string]interface{}, template GetSubmitterResponseTemplate, submissionEvents []GetSubmissionResponseSubmissionEventsInner, values []CreateSubmissionResponseInnerValuesInner, documents []GetSubmissionResponseSubmittersInnerDocumentsInner, role string) *GetSubmitterResponse {
	this := GetSubmitterResponse{}
	this.Id = id
	this.SubmissionId = submissionId
	this.Uuid = uuid
	this.Email = email
	this.Slug = slug
	this.SentAt = sentAt
	this.OpenedAt = openedAt
	this.CompletedAt = completedAt
	this.DeclinedAt = declinedAt
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Name = name
	this.Phone = phone
	this.Status = status
	this.ExternalId = externalId
	this.Metadata = metadata
	this.Preferences = preferences
	this.Template = template
	this.SubmissionEvents = submissionEvents
	this.Values = values
	this.Documents = documents
	this.Role = role
	return &this
}

// NewGetSubmitterResponseWithDefaults instantiates a new GetSubmitterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSubmitterResponseWithDefaults() *GetSubmitterResponse {
	this := GetSubmitterResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GetSubmitterResponse) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetSubmitterResponse) SetId(v int32) {
	o.Id = v
}

// GetSubmissionId returns the SubmissionId field value
func (o *GetSubmitterResponse) GetSubmissionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SubmissionId
}

// GetSubmissionIdOk returns a tuple with the SubmissionId field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetSubmissionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubmissionId, true
}

// SetSubmissionId sets field value
func (o *GetSubmitterResponse) SetSubmissionId(v int32) {
	o.SubmissionId = v
}

// GetUuid returns the Uuid field value
func (o *GetSubmitterResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *GetSubmitterResponse) SetUuid(v string) {
	o.Uuid = v
}

// GetEmail returns the Email field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmitterResponse) GetEmail() string {
	if o == nil || o.Email.Get() == nil {
		var ret string
		return ret
	}

	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmitterResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// SetEmail sets field value
func (o *GetSubmitterResponse) SetEmail(v string) {
	o.Email.Set(&v)
}

// GetSlug returns the Slug field value
func (o *GetSubmitterResponse) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *GetSubmitterResponse) SetSlug(v string) {
	o.Slug = v
}

// GetSentAt returns the SentAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmitterResponse) GetSentAt() string {
	if o == nil || o.SentAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.SentAt.Get()
}

// GetSentAtOk returns a tuple with the SentAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmitterResponse) GetSentAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SentAt.Get(), o.SentAt.IsSet()
}

// SetSentAt sets field value
func (o *GetSubmitterResponse) SetSentAt(v string) {
	o.SentAt.Set(&v)
}

// GetOpenedAt returns the OpenedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmitterResponse) GetOpenedAt() string {
	if o == nil || o.OpenedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.OpenedAt.Get()
}

// GetOpenedAtOk returns a tuple with the OpenedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmitterResponse) GetOpenedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpenedAt.Get(), o.OpenedAt.IsSet()
}

// SetOpenedAt sets field value
func (o *GetSubmitterResponse) SetOpenedAt(v string) {
	o.OpenedAt.Set(&v)
}

// GetCompletedAt returns the CompletedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmitterResponse) GetCompletedAt() string {
	if o == nil || o.CompletedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmitterResponse) GetCompletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// SetCompletedAt sets field value
func (o *GetSubmitterResponse) SetCompletedAt(v string) {
	o.CompletedAt.Set(&v)
}

// GetDeclinedAt returns the DeclinedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmitterResponse) GetDeclinedAt() string {
	if o == nil || o.DeclinedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.DeclinedAt.Get()
}

// GetDeclinedAtOk returns a tuple with the DeclinedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmitterResponse) GetDeclinedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeclinedAt.Get(), o.DeclinedAt.IsSet()
}

// SetDeclinedAt sets field value
func (o *GetSubmitterResponse) SetDeclinedAt(v string) {
	o.DeclinedAt.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetSubmitterResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetSubmitterResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetSubmitterResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetSubmitterResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmitterResponse) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmitterResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *GetSubmitterResponse) SetName(v string) {
	o.Name.Set(&v)
}

// GetPhone returns the Phone field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmitterResponse) GetPhone() string {
	if o == nil || o.Phone.Get() == nil {
		var ret string
		return ret
	}

	return *o.Phone.Get()
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmitterResponse) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phone.Get(), o.Phone.IsSet()
}

// SetPhone sets field value
func (o *GetSubmitterResponse) SetPhone(v string) {
	o.Phone.Set(&v)
}

// GetStatus returns the Status field value
func (o *GetSubmitterResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetSubmitterResponse) SetStatus(v string) {
	o.Status = v
}

// GetExternalId returns the ExternalId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmitterResponse) GetExternalId() string {
	if o == nil || o.ExternalId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmitterResponse) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// SetExternalId sets field value
func (o *GetSubmitterResponse) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// GetMetadata returns the Metadata field value
func (o *GetSubmitterResponse) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *GetSubmitterResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPreferences returns the Preferences field value
func (o *GetSubmitterResponse) GetPreferences() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetPreferencesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Preferences, true
}

// SetPreferences sets field value
func (o *GetSubmitterResponse) SetPreferences(v map[string]interface{}) {
	o.Preferences = v
}

// GetTemplate returns the Template field value
func (o *GetSubmitterResponse) GetTemplate() GetSubmitterResponseTemplate {
	if o == nil {
		var ret GetSubmitterResponseTemplate
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetTemplateOk() (*GetSubmitterResponseTemplate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *GetSubmitterResponse) SetTemplate(v GetSubmitterResponseTemplate) {
	o.Template = v
}

// GetSubmissionEvents returns the SubmissionEvents field value
func (o *GetSubmitterResponse) GetSubmissionEvents() []GetSubmissionResponseSubmissionEventsInner {
	if o == nil {
		var ret []GetSubmissionResponseSubmissionEventsInner
		return ret
	}

	return o.SubmissionEvents
}

// GetSubmissionEventsOk returns a tuple with the SubmissionEvents field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetSubmissionEventsOk() ([]GetSubmissionResponseSubmissionEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubmissionEvents, true
}

// SetSubmissionEvents sets field value
func (o *GetSubmitterResponse) SetSubmissionEvents(v []GetSubmissionResponseSubmissionEventsInner) {
	o.SubmissionEvents = v
}

// GetValues returns the Values field value
func (o *GetSubmitterResponse) GetValues() []CreateSubmissionResponseInnerValuesInner {
	if o == nil {
		var ret []CreateSubmissionResponseInnerValuesInner
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetValuesOk() ([]CreateSubmissionResponseInnerValuesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *GetSubmitterResponse) SetValues(v []CreateSubmissionResponseInnerValuesInner) {
	o.Values = v
}

// GetDocuments returns the Documents field value
func (o *GetSubmitterResponse) GetDocuments() []GetSubmissionResponseSubmittersInnerDocumentsInner {
	if o == nil {
		var ret []GetSubmissionResponseSubmittersInnerDocumentsInner
		return ret
	}

	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetDocumentsOk() ([]GetSubmissionResponseSubmittersInnerDocumentsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Documents, true
}

// SetDocuments sets field value
func (o *GetSubmitterResponse) SetDocuments(v []GetSubmissionResponseSubmittersInnerDocumentsInner) {
	o.Documents = v
}

// GetRole returns the Role field value
func (o *GetSubmitterResponse) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *GetSubmitterResponse) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *GetSubmitterResponse) SetRole(v string) {
	o.Role = v
}

func (o GetSubmitterResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSubmitterResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["submission_id"] = o.SubmissionId
	toSerialize["uuid"] = o.Uuid
	toSerialize["email"] = o.Email.Get()
	toSerialize["slug"] = o.Slug
	toSerialize["sent_at"] = o.SentAt.Get()
	toSerialize["opened_at"] = o.OpenedAt.Get()
	toSerialize["completed_at"] = o.CompletedAt.Get()
	toSerialize["declined_at"] = o.DeclinedAt.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["name"] = o.Name.Get()
	toSerialize["phone"] = o.Phone.Get()
	toSerialize["status"] = o.Status
	toSerialize["external_id"] = o.ExternalId.Get()
	toSerialize["metadata"] = o.Metadata
	toSerialize["preferences"] = o.Preferences
	toSerialize["template"] = o.Template
	toSerialize["submission_events"] = o.SubmissionEvents
	toSerialize["values"] = o.Values
	toSerialize["documents"] = o.Documents
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *GetSubmitterResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"submission_id",
		"uuid",
		"email",
		"slug",
		"sent_at",
		"opened_at",
		"completed_at",
		"declined_at",
		"created_at",
		"updated_at",
		"name",
		"phone",
		"status",
		"external_id",
		"metadata",
		"preferences",
		"template",
		"submission_events",
		"values",
		"documents",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSubmitterResponse := _GetSubmitterResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSubmitterResponse)

	if err != nil {
		return err
	}

	*o = GetSubmitterResponse(varGetSubmitterResponse)

	return err
}

type NullableGetSubmitterResponse struct {
	value *GetSubmitterResponse
	isSet bool
}

func (v NullableGetSubmitterResponse) Get() *GetSubmitterResponse {
	return v.value
}

func (v *NullableGetSubmitterResponse) Set(val *GetSubmitterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSubmitterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSubmitterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSubmitterResponse(val *GetSubmitterResponse) *NullableGetSubmitterResponse {
	return &NullableGetSubmitterResponse{value: val, isSet: true}
}

func (v NullableGetSubmitterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSubmitterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
