/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetSubmissionsResponseDataInnerSubmittersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSubmissionsResponseDataInnerSubmittersInner{}

// GetSubmissionsResponseDataInnerSubmittersInner struct for GetSubmissionsResponseDataInnerSubmittersInner
type GetSubmissionsResponseDataInnerSubmittersInner struct {
	// Submitter unique ID number.
	Id int32 `json:"id"`
	// Submission unique ID number.
	SubmissionId int32 `json:"submission_id"`
	// Submitter UUID.
	Uuid string `json:"uuid"`
	// The email address of the submitter.
	Email NullableString `json:"email"`
	// Unique key to be used in the form signing link and embedded form.
	Slug string `json:"slug"`
	// The date and time when the signing request was sent to the submitter.
	SentAt NullableString `json:"sent_at"`
	// The date and time when the submitter opened the signing form.
	OpenedAt NullableString `json:"opened_at"`
	// The date and time when the submitter completed the signing form.
	CompletedAt NullableString `json:"completed_at"`
	// The date and time when the submitter declined the signing form.
	DeclinedAt NullableString `json:"declined_at"`
	// The date and time when the submitter was created.
	CreatedAt string `json:"created_at"`
	// The date and time when the submitter was last updated.
	UpdatedAt string `json:"updated_at"`
	// The name of the submitter.
	Name NullableString `json:"name"`
	// The phone number of the submitter.
	Phone NullableString `json:"phone"`
	// Your application-specific unique string key to identify this submitter within your app.
	ExternalId NullableString `json:"external_id,omitempty"`
	// The status of signing request for the submitter.
	Status string `json:"status"`
	// The role of the submitter in the signing process.
	Role string `json:"role"`
	// Metadata object with additional submitter information.
	Metadata map[string]interface{} `json:"metadata"`
	// Submitter preferences.
	Preferences map[string]interface{} `json:"preferences"`
}

type _GetSubmissionsResponseDataInnerSubmittersInner GetSubmissionsResponseDataInnerSubmittersInner

// NewGetSubmissionsResponseDataInnerSubmittersInner instantiates a new GetSubmissionsResponseDataInnerSubmittersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSubmissionsResponseDataInnerSubmittersInner(id int32, submissionId int32, uuid string, email NullableString, slug string, sentAt NullableString, openedAt NullableString, completedAt NullableString, declinedAt NullableString, createdAt string, updatedAt string, name NullableString, phone NullableString, status string, role string, metadata map[string]interface{}, preferences map[string]interface{}) *GetSubmissionsResponseDataInnerSubmittersInner {
	this := GetSubmissionsResponseDataInnerSubmittersInner{}
	this.Id = id
	this.SubmissionId = submissionId
	this.Uuid = uuid
	this.Email = email
	this.Slug = slug
	this.SentAt = sentAt
	this.OpenedAt = openedAt
	this.CompletedAt = completedAt
	this.DeclinedAt = declinedAt
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Name = name
	this.Phone = phone
	this.Status = status
	this.Role = role
	this.Metadata = metadata
	this.Preferences = preferences
	return &this
}

// NewGetSubmissionsResponseDataInnerSubmittersInnerWithDefaults instantiates a new GetSubmissionsResponseDataInnerSubmittersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSubmissionsResponseDataInnerSubmittersInnerWithDefaults() *GetSubmissionsResponseDataInnerSubmittersInner {
	this := GetSubmissionsResponseDataInnerSubmittersInner{}
	return &this
}

// GetId returns the Id field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetId(v int32) {
	o.Id = v
}

// GetSubmissionId returns the SubmissionId field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetSubmissionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SubmissionId
}

// GetSubmissionIdOk returns a tuple with the SubmissionId field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetSubmissionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubmissionId, true
}

// SetSubmissionId sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetSubmissionId(v int32) {
	o.SubmissionId = v
}

// GetUuid returns the Uuid field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetUuid(v string) {
	o.Uuid = v
}

// GetEmail returns the Email field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetEmail() string {
	if o == nil || o.Email.Get() == nil {
		var ret string
		return ret
	}

	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// SetEmail sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetEmail(v string) {
	o.Email.Set(&v)
}

// GetSlug returns the Slug field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetSlug(v string) {
	o.Slug = v
}

// GetSentAt returns the SentAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetSentAt() string {
	if o == nil || o.SentAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.SentAt.Get()
}

// GetSentAtOk returns a tuple with the SentAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetSentAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SentAt.Get(), o.SentAt.IsSet()
}

// SetSentAt sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetSentAt(v string) {
	o.SentAt.Set(&v)
}

// GetOpenedAt returns the OpenedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetOpenedAt() string {
	if o == nil || o.OpenedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.OpenedAt.Get()
}

// GetOpenedAtOk returns a tuple with the OpenedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetOpenedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpenedAt.Get(), o.OpenedAt.IsSet()
}

// SetOpenedAt sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetOpenedAt(v string) {
	o.OpenedAt.Set(&v)
}

// GetCompletedAt returns the CompletedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetCompletedAt() string {
	if o == nil || o.CompletedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetCompletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// SetCompletedAt sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetCompletedAt(v string) {
	o.CompletedAt.Set(&v)
}

// GetDeclinedAt returns the DeclinedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetDeclinedAt() string {
	if o == nil || o.DeclinedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.DeclinedAt.Get()
}

// GetDeclinedAtOk returns a tuple with the DeclinedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetDeclinedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeclinedAt.Get(), o.DeclinedAt.IsSet()
}

// SetDeclinedAt sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetDeclinedAt(v string) {
	o.DeclinedAt.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetName(v string) {
	o.Name.Set(&v)
}

// GetPhone returns the Phone field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetPhone() string {
	if o == nil || o.Phone.Get() == nil {
		var ret string
		return ret
	}

	return *o.Phone.Get()
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phone.Get(), o.Phone.IsSet()
}

// SetPhone sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetPhone(v string) {
	o.Phone.Set(&v)
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *GetSubmissionsResponseDataInnerSubmittersInner) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetStatus returns the Status field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetStatus(v string) {
	o.Status = v
}

// GetRole returns the Role field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetRole(v string) {
	o.Role = v
}

// GetMetadata returns the Metadata field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPreferences returns the Preferences field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetPreferences() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionsResponseDataInnerSubmittersInner) GetPreferencesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Preferences, true
}

// SetPreferences sets field value
func (o *GetSubmissionsResponseDataInnerSubmittersInner) SetPreferences(v map[string]interface{}) {
	o.Preferences = v
}

func (o GetSubmissionsResponseDataInnerSubmittersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSubmissionsResponseDataInnerSubmittersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["submission_id"] = o.SubmissionId
	toSerialize["uuid"] = o.Uuid
	toSerialize["email"] = o.Email.Get()
	toSerialize["slug"] = o.Slug
	toSerialize["sent_at"] = o.SentAt.Get()
	toSerialize["opened_at"] = o.OpenedAt.Get()
	toSerialize["completed_at"] = o.CompletedAt.Get()
	toSerialize["declined_at"] = o.DeclinedAt.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["name"] = o.Name.Get()
	toSerialize["phone"] = o.Phone.Get()
	if o.ExternalId.IsSet() {
		toSerialize["external_id"] = o.ExternalId.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["role"] = o.Role
	toSerialize["metadata"] = o.Metadata
	toSerialize["preferences"] = o.Preferences
	return toSerialize, nil
}

func (o *GetSubmissionsResponseDataInnerSubmittersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"submission_id",
		"uuid",
		"email",
		"slug",
		"sent_at",
		"opened_at",
		"completed_at",
		"declined_at",
		"created_at",
		"updated_at",
		"name",
		"phone",
		"status",
		"role",
		"metadata",
		"preferences",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSubmissionsResponseDataInnerSubmittersInner := _GetSubmissionsResponseDataInnerSubmittersInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSubmissionsResponseDataInnerSubmittersInner)

	if err != nil {
		return err
	}

	*o = GetSubmissionsResponseDataInnerSubmittersInner(varGetSubmissionsResponseDataInnerSubmittersInner)

	return err
}

type NullableGetSubmissionsResponseDataInnerSubmittersInner struct {
	value *GetSubmissionsResponseDataInnerSubmittersInner
	isSet bool
}

func (v NullableGetSubmissionsResponseDataInnerSubmittersInner) Get() *GetSubmissionsResponseDataInnerSubmittersInner {
	return v.value
}

func (v *NullableGetSubmissionsResponseDataInnerSubmittersInner) Set(val *GetSubmissionsResponseDataInnerSubmittersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSubmissionsResponseDataInnerSubmittersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSubmissionsResponseDataInnerSubmittersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSubmissionsResponseDataInnerSubmittersInner(val *GetSubmissionsResponseDataInnerSubmittersInner) *NullableGetSubmissionsResponseDataInnerSubmittersInner {
	return &NullableGetSubmissionsResponseDataInnerSubmittersInner{value: val, isSet: true}
}

func (v NullableGetSubmissionsResponseDataInnerSubmittersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSubmissionsResponseDataInnerSubmittersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
