/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetTemplatesResponseDataInnerAuthor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTemplatesResponseDataInnerAuthor{}

// GetTemplatesResponseDataInnerAuthor struct for GetTemplatesResponseDataInnerAuthor
type GetTemplatesResponseDataInnerAuthor struct {
	// Unique identifier of the author.
	Id int32 `json:"id"`
	// First name of the author.
	FirstName string `json:"first_name"`
	// Last name of the author.
	LastName string `json:"last_name"`
	// Author email.
	Email string `json:"email"`
}

type _GetTemplatesResponseDataInnerAuthor GetTemplatesResponseDataInnerAuthor

// NewGetTemplatesResponseDataInnerAuthor instantiates a new GetTemplatesResponseDataInnerAuthor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTemplatesResponseDataInnerAuthor(id int32, firstName string, lastName string, email string) *GetTemplatesResponseDataInnerAuthor {
	this := GetTemplatesResponseDataInnerAuthor{}
	this.Id = id
	this.FirstName = firstName
	this.LastName = lastName
	this.Email = email
	return &this
}

// NewGetTemplatesResponseDataInnerAuthorWithDefaults instantiates a new GetTemplatesResponseDataInnerAuthor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTemplatesResponseDataInnerAuthorWithDefaults() *GetTemplatesResponseDataInnerAuthor {
	this := GetTemplatesResponseDataInnerAuthor{}
	return &this
}

// GetId returns the Id field value
func (o *GetTemplatesResponseDataInnerAuthor) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerAuthor) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetTemplatesResponseDataInnerAuthor) SetId(v int32) {
	o.Id = v
}

// GetFirstName returns the FirstName field value
func (o *GetTemplatesResponseDataInnerAuthor) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerAuthor) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *GetTemplatesResponseDataInnerAuthor) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *GetTemplatesResponseDataInnerAuthor) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerAuthor) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *GetTemplatesResponseDataInnerAuthor) SetLastName(v string) {
	o.LastName = v
}

// GetEmail returns the Email field value
func (o *GetTemplatesResponseDataInnerAuthor) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *GetTemplatesResponseDataInnerAuthor) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *GetTemplatesResponseDataInnerAuthor) SetEmail(v string) {
	o.Email = v
}

func (o GetTemplatesResponseDataInnerAuthor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTemplatesResponseDataInnerAuthor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["first_name"] = o.FirstName
	toSerialize["last_name"] = o.LastName
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *GetTemplatesResponseDataInnerAuthor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"first_name",
		"last_name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetTemplatesResponseDataInnerAuthor := _GetTemplatesResponseDataInnerAuthor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetTemplatesResponseDataInnerAuthor)

	if err != nil {
		return err
	}

	*o = GetTemplatesResponseDataInnerAuthor(varGetTemplatesResponseDataInnerAuthor)

	return err
}

type NullableGetTemplatesResponseDataInnerAuthor struct {
	value *GetTemplatesResponseDataInnerAuthor
	isSet bool
}

func (v NullableGetTemplatesResponseDataInnerAuthor) Get() *GetTemplatesResponseDataInnerAuthor {
	return v.value
}

func (v *NullableGetTemplatesResponseDataInnerAuthor) Set(val *GetTemplatesResponseDataInnerAuthor) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTemplatesResponseDataInnerAuthor) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTemplatesResponseDataInnerAuthor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTemplatesResponseDataInnerAuthor(val *GetTemplatesResponseDataInnerAuthor) *NullableGetTemplatesResponseDataInnerAuthor {
	return &NullableGetTemplatesResponseDataInnerAuthor{value: val, isSet: true}
}

func (v NullableGetTemplatesResponseDataInnerAuthor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTemplatesResponseDataInnerAuthor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
