/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetSubmissionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSubmissionResponse{}

// GetSubmissionResponse struct for GetSubmissionResponse
type GetSubmissionResponse struct {
	// Submission unique ID number.
	Id int32 `json:"id"`
	// Name of the document submission.
	Name *string `json:"name,omitempty"`
	// Unique slug of the submission.
	Slug string `json:"slug"`
	// The source of the submission.
	Source string `json:"source"`
	// The order of submitters.
	SubmittersOrder string `json:"submitters_order"`
	// Audit log file URL.
	AuditLogUrl NullableString `json:"audit_log_url"`
	// Combined PDF file URL with documents and Audit Log.
	CombinedDocumentUrl NullableString `json:"combined_document_url"`
	// The date and time when the submission was created.
	CreatedAt string `json:"created_at"`
	// The date and time when the submission was last updated.
	UpdatedAt string `json:"updated_at"`
	// The date and time when the submission was archived.
	ArchivedAt NullableString `json:"archived_at"`
	// The list of submitters.
	Submitters    []GetSubmissionResponseSubmittersInner       `json:"submitters"`
	Template      *GetSubmissionsResponseDataInnerTemplate     `json:"template,omitempty"`
	CreatedByUser GetSubmissionsResponseDataInnerCreatedByUser `json:"created_by_user"`
	// An array of events related to the submission.
	SubmissionEvents []GetSubmissionResponseSubmissionEventsInner `json:"submission_events"`
	// An array of completed or signed documents of the submission.
	Documents []GetSubmissionResponseSubmittersInnerDocumentsInner `json:"documents"`
	// The status of the submission.
	Status string `json:"status"`
	// Object with custom metadata.
	Metadata map[string]interface{} `json:"metadata"`
	// The date and time when the submission was completed.
	CompletedAt NullableString `json:"completed_at"`
}

type _GetSubmissionResponse GetSubmissionResponse

// NewGetSubmissionResponse instantiates a new GetSubmissionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSubmissionResponse(id int32, slug string, source string, submittersOrder string, auditLogUrl NullableString, combinedDocumentUrl NullableString, createdAt string, updatedAt string, archivedAt NullableString, submitters []GetSubmissionResponseSubmittersInner, createdByUser GetSubmissionsResponseDataInnerCreatedByUser, submissionEvents []GetSubmissionResponseSubmissionEventsInner, documents []GetSubmissionResponseSubmittersInnerDocumentsInner, status string, metadata map[string]interface{}, completedAt NullableString) *GetSubmissionResponse {
	this := GetSubmissionResponse{}
	this.Id = id
	this.Slug = slug
	this.Source = source
	this.SubmittersOrder = submittersOrder
	this.AuditLogUrl = auditLogUrl
	this.CombinedDocumentUrl = combinedDocumentUrl
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.ArchivedAt = archivedAt
	this.Submitters = submitters
	this.CreatedByUser = createdByUser
	this.SubmissionEvents = submissionEvents
	this.Documents = documents
	this.Status = status
	this.Metadata = metadata
	this.CompletedAt = completedAt
	return &this
}

// NewGetSubmissionResponseWithDefaults instantiates a new GetSubmissionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSubmissionResponseWithDefaults() *GetSubmissionResponse {
	this := GetSubmissionResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GetSubmissionResponse) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetSubmissionResponse) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetSubmissionResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetSubmissionResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetSubmissionResponse) SetName(v string) {
	o.Name = &v
}

// GetSlug returns the Slug field value
func (o *GetSubmissionResponse) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *GetSubmissionResponse) SetSlug(v string) {
	o.Slug = v
}

// GetSource returns the Source field value
func (o *GetSubmissionResponse) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *GetSubmissionResponse) SetSource(v string) {
	o.Source = v
}

// GetSubmittersOrder returns the SubmittersOrder field value
func (o *GetSubmissionResponse) GetSubmittersOrder() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubmittersOrder
}

// GetSubmittersOrderOk returns a tuple with the SubmittersOrder field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetSubmittersOrderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubmittersOrder, true
}

// SetSubmittersOrder sets field value
func (o *GetSubmissionResponse) SetSubmittersOrder(v string) {
	o.SubmittersOrder = v
}

// GetAuditLogUrl returns the AuditLogUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionResponse) GetAuditLogUrl() string {
	if o == nil || o.AuditLogUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.AuditLogUrl.Get()
}

// GetAuditLogUrlOk returns a tuple with the AuditLogUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionResponse) GetAuditLogUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuditLogUrl.Get(), o.AuditLogUrl.IsSet()
}

// SetAuditLogUrl sets field value
func (o *GetSubmissionResponse) SetAuditLogUrl(v string) {
	o.AuditLogUrl.Set(&v)
}

// GetCombinedDocumentUrl returns the CombinedDocumentUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionResponse) GetCombinedDocumentUrl() string {
	if o == nil || o.CombinedDocumentUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.CombinedDocumentUrl.Get()
}

// GetCombinedDocumentUrlOk returns a tuple with the CombinedDocumentUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionResponse) GetCombinedDocumentUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CombinedDocumentUrl.Get(), o.CombinedDocumentUrl.IsSet()
}

// SetCombinedDocumentUrl sets field value
func (o *GetSubmissionResponse) SetCombinedDocumentUrl(v string) {
	o.CombinedDocumentUrl.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetSubmissionResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetSubmissionResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetSubmissionResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetSubmissionResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetArchivedAt returns the ArchivedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionResponse) GetArchivedAt() string {
	if o == nil || o.ArchivedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.ArchivedAt.Get()
}

// GetArchivedAtOk returns a tuple with the ArchivedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionResponse) GetArchivedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArchivedAt.Get(), o.ArchivedAt.IsSet()
}

// SetArchivedAt sets field value
func (o *GetSubmissionResponse) SetArchivedAt(v string) {
	o.ArchivedAt.Set(&v)
}

// GetSubmitters returns the Submitters field value
func (o *GetSubmissionResponse) GetSubmitters() []GetSubmissionResponseSubmittersInner {
	if o == nil {
		var ret []GetSubmissionResponseSubmittersInner
		return ret
	}

	return o.Submitters
}

// GetSubmittersOk returns a tuple with the Submitters field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetSubmittersOk() ([]GetSubmissionResponseSubmittersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Submitters, true
}

// SetSubmitters sets field value
func (o *GetSubmissionResponse) SetSubmitters(v []GetSubmissionResponseSubmittersInner) {
	o.Submitters = v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *GetSubmissionResponse) GetTemplate() GetSubmissionsResponseDataInnerTemplate {
	if o == nil || IsNil(o.Template) {
		var ret GetSubmissionsResponseDataInnerTemplate
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetTemplateOk() (*GetSubmissionsResponseDataInnerTemplate, bool) {
	if o == nil || IsNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *GetSubmissionResponse) HasTemplate() bool {
	if o != nil && !IsNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given GetSubmissionsResponseDataInnerTemplate and assigns it to the Template field.
func (o *GetSubmissionResponse) SetTemplate(v GetSubmissionsResponseDataInnerTemplate) {
	o.Template = &v
}

// GetCreatedByUser returns the CreatedByUser field value
func (o *GetSubmissionResponse) GetCreatedByUser() GetSubmissionsResponseDataInnerCreatedByUser {
	if o == nil {
		var ret GetSubmissionsResponseDataInnerCreatedByUser
		return ret
	}

	return o.CreatedByUser
}

// GetCreatedByUserOk returns a tuple with the CreatedByUser field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetCreatedByUserOk() (*GetSubmissionsResponseDataInnerCreatedByUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByUser, true
}

// SetCreatedByUser sets field value
func (o *GetSubmissionResponse) SetCreatedByUser(v GetSubmissionsResponseDataInnerCreatedByUser) {
	o.CreatedByUser = v
}

// GetSubmissionEvents returns the SubmissionEvents field value
func (o *GetSubmissionResponse) GetSubmissionEvents() []GetSubmissionResponseSubmissionEventsInner {
	if o == nil {
		var ret []GetSubmissionResponseSubmissionEventsInner
		return ret
	}

	return o.SubmissionEvents
}

// GetSubmissionEventsOk returns a tuple with the SubmissionEvents field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetSubmissionEventsOk() ([]GetSubmissionResponseSubmissionEventsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubmissionEvents, true
}

// SetSubmissionEvents sets field value
func (o *GetSubmissionResponse) SetSubmissionEvents(v []GetSubmissionResponseSubmissionEventsInner) {
	o.SubmissionEvents = v
}

// GetDocuments returns the Documents field value
func (o *GetSubmissionResponse) GetDocuments() []GetSubmissionResponseSubmittersInnerDocumentsInner {
	if o == nil {
		var ret []GetSubmissionResponseSubmittersInnerDocumentsInner
		return ret
	}

	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetDocumentsOk() ([]GetSubmissionResponseSubmittersInnerDocumentsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Documents, true
}

// SetDocuments sets field value
func (o *GetSubmissionResponse) SetDocuments(v []GetSubmissionResponseSubmittersInnerDocumentsInner) {
	o.Documents = v
}

// GetStatus returns the Status field value
func (o *GetSubmissionResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetSubmissionResponse) SetStatus(v string) {
	o.Status = v
}

// GetMetadata returns the Metadata field value
func (o *GetSubmissionResponse) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *GetSubmissionResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *GetSubmissionResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetCompletedAt returns the CompletedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetSubmissionResponse) GetCompletedAt() string {
	if o == nil || o.CompletedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSubmissionResponse) GetCompletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// SetCompletedAt sets field value
func (o *GetSubmissionResponse) SetCompletedAt(v string) {
	o.CompletedAt.Set(&v)
}

func (o GetSubmissionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSubmissionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["slug"] = o.Slug
	toSerialize["source"] = o.Source
	toSerialize["submitters_order"] = o.SubmittersOrder
	toSerialize["audit_log_url"] = o.AuditLogUrl.Get()
	toSerialize["combined_document_url"] = o.CombinedDocumentUrl.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["archived_at"] = o.ArchivedAt.Get()
	toSerialize["submitters"] = o.Submitters
	if !IsNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	toSerialize["created_by_user"] = o.CreatedByUser
	toSerialize["submission_events"] = o.SubmissionEvents
	toSerialize["documents"] = o.Documents
	toSerialize["status"] = o.Status
	toSerialize["metadata"] = o.Metadata
	toSerialize["completed_at"] = o.CompletedAt.Get()
	return toSerialize, nil
}

func (o *GetSubmissionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"slug",
		"source",
		"submitters_order",
		"audit_log_url",
		"combined_document_url",
		"created_at",
		"updated_at",
		"archived_at",
		"submitters",
		"created_by_user",
		"submission_events",
		"documents",
		"status",
		"metadata",
		"completed_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSubmissionResponse := _GetSubmissionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSubmissionResponse)

	if err != nil {
		return err
	}

	*o = GetSubmissionResponse(varGetSubmissionResponse)

	return err
}

type NullableGetSubmissionResponse struct {
	value *GetSubmissionResponse
	isSet bool
}

func (v NullableGetSubmissionResponse) Get() *GetSubmissionResponse {
	return v.value
}

func (v *NullableGetSubmissionResponse) Set(val *GetSubmissionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSubmissionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSubmissionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSubmissionResponse(val *GetSubmissionResponse) *NullableGetSubmissionResponse {
	return &NullableGetSubmissionResponse{value: val, isSet: true}
}

func (v NullableGetSubmissionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSubmissionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
