/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the SubmissionWebhookRequestDataTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmissionWebhookRequestDataTemplate{}

// SubmissionWebhookRequestDataTemplate Base template details.
type SubmissionWebhookRequestDataTemplate struct {
	// The template's unique identifier.
	Id *float32 `json:"id,omitempty"`
	// The template's name.
	Name *string `json:"name,omitempty"`
	// Your application-specific unique string key to identify template within your app.
	ExternalId *string `json:"external_id,omitempty"`
	// The folder name.
	FolderName *string `json:"folder_name,omitempty"`
	// The date and time when the template was created.
	CreatedAt *string `json:"created_at,omitempty"`
	// The date and time when the template was last updated.
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// NewSubmissionWebhookRequestDataTemplate instantiates a new SubmissionWebhookRequestDataTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmissionWebhookRequestDataTemplate() *SubmissionWebhookRequestDataTemplate {
	this := SubmissionWebhookRequestDataTemplate{}
	return &this
}

// NewSubmissionWebhookRequestDataTemplateWithDefaults instantiates a new SubmissionWebhookRequestDataTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmissionWebhookRequestDataTemplateWithDefaults() *SubmissionWebhookRequestDataTemplate {
	this := SubmissionWebhookRequestDataTemplate{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataTemplate) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataTemplate) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataTemplate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *SubmissionWebhookRequestDataTemplate) SetId(v float32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataTemplate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataTemplate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataTemplate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SubmissionWebhookRequestDataTemplate) SetName(v string) {
	o.Name = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataTemplate) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataTemplate) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataTemplate) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *SubmissionWebhookRequestDataTemplate) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetFolderName returns the FolderName field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataTemplate) GetFolderName() string {
	if o == nil || IsNil(o.FolderName) {
		var ret string
		return ret
	}
	return *o.FolderName
}

// GetFolderNameOk returns a tuple with the FolderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataTemplate) GetFolderNameOk() (*string, bool) {
	if o == nil || IsNil(o.FolderName) {
		return nil, false
	}
	return o.FolderName, true
}

// HasFolderName returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataTemplate) HasFolderName() bool {
	if o != nil && !IsNil(o.FolderName) {
		return true
	}

	return false
}

// SetFolderName gets a reference to the given string and assigns it to the FolderName field.
func (o *SubmissionWebhookRequestDataTemplate) SetFolderName(v string) {
	o.FolderName = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataTemplate) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataTemplate) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataTemplate) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *SubmissionWebhookRequestDataTemplate) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataTemplate) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataTemplate) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataTemplate) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *SubmissionWebhookRequestDataTemplate) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o SubmissionWebhookRequestDataTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmissionWebhookRequestDataTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !IsNil(o.FolderName) {
		toSerialize["folder_name"] = o.FolderName
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableSubmissionWebhookRequestDataTemplate struct {
	value *SubmissionWebhookRequestDataTemplate
	isSet bool
}

func (v NullableSubmissionWebhookRequestDataTemplate) Get() *SubmissionWebhookRequestDataTemplate {
	return v.value
}

func (v *NullableSubmissionWebhookRequestDataTemplate) Set(val *SubmissionWebhookRequestDataTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmissionWebhookRequestDataTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmissionWebhookRequestDataTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmissionWebhookRequestDataTemplate(val *SubmissionWebhookRequestDataTemplate) *NullableSubmissionWebhookRequestDataTemplate {
	return &NullableSubmissionWebhookRequestDataTemplate{value: val, isSet: true}
}

func (v NullableSubmissionWebhookRequestDataTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmissionWebhookRequestDataTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
