/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the SubmissionWebhookRequestDataSubmittersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmissionWebhookRequestDataSubmittersInner{}

// SubmissionWebhookRequestDataSubmittersInner struct for SubmissionWebhookRequestDataSubmittersInner
type SubmissionWebhookRequestDataSubmittersInner struct {
	// The submitter's unique identifier.
	Id *float32 `json:"id,omitempty"`
	// The unique submission identifier.
	SubmissionId *float32 `json:"submission_id,omitempty"`
	// The submitter UUID.
	Uuid *string `json:"uuid,omitempty"`
	// The email address of the submitter.
	Email *string `json:"email,omitempty"`
	// The unique slug of the document template.
	Slug *string `json:"slug,omitempty"`
	// The date and time when the signing request was sent to the submitter.
	SentAt NullableString `json:"sent_at,omitempty"`
	// The date and time when the submitter opened the signing form.
	OpenedAt NullableString `json:"opened_at,omitempty"`
	// The date and time when the submitter completed the signing form.
	CompletedAt NullableString `json:"completed_at,omitempty"`
	// The date and time when the submitter declined the signing form.
	DeclinedAt NullableString `json:"declined_at,omitempty"`
	// The date and time when the submitter was created.
	CreatedAt *string `json:"created_at,omitempty"`
	// The date and time when the submitter was last updated.
	UpdatedAt *string `json:"updated_at,omitempty"`
	// The name of the submitter.
	Name NullableString `json:"name,omitempty"`
	// The phone number of the submitter, formatted according to the E.164 standard.
	Phone *string `json:"phone,omitempty"`
	// The role name or title of the submitter.
	Role *string `json:"role,omitempty"`
	// Your application-specific unique string key to identify this submitter within your app.
	ExternalId NullableString `json:"external_id,omitempty"`
	// Metadata object with additional submitter information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// The submitter status.
	Status *string `json:"status,omitempty"`
	// An object with pre-filled values for the submission. Use field names for keys of the object. For more configurations see `fields` param.
	Values map[string]interface{} `json:"values,omitempty"`
	// The list of documents for the submission.
	Documents []FormWebhookRequestDataDocumentsInner `json:"documents,omitempty"`
	// The submitter preferences.
	Preferences map[string]interface{} `json:"preferences,omitempty"`
}

// NewSubmissionWebhookRequestDataSubmittersInner instantiates a new SubmissionWebhookRequestDataSubmittersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmissionWebhookRequestDataSubmittersInner() *SubmissionWebhookRequestDataSubmittersInner {
	this := SubmissionWebhookRequestDataSubmittersInner{}
	return &this
}

// NewSubmissionWebhookRequestDataSubmittersInnerWithDefaults instantiates a new SubmissionWebhookRequestDataSubmittersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmissionWebhookRequestDataSubmittersInnerWithDefaults() *SubmissionWebhookRequestDataSubmittersInner {
	this := SubmissionWebhookRequestDataSubmittersInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetId(v float32) {
	o.Id = &v
}

// GetSubmissionId returns the SubmissionId field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetSubmissionId() float32 {
	if o == nil || IsNil(o.SubmissionId) {
		var ret float32
		return ret
	}
	return *o.SubmissionId
}

// GetSubmissionIdOk returns a tuple with the SubmissionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetSubmissionIdOk() (*float32, bool) {
	if o == nil || IsNil(o.SubmissionId) {
		return nil, false
	}
	return o.SubmissionId, true
}

// HasSubmissionId returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasSubmissionId() bool {
	if o != nil && !IsNil(o.SubmissionId) {
		return true
	}

	return false
}

// SetSubmissionId gets a reference to the given float32 and assigns it to the SubmissionId field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetSubmissionId(v float32) {
	o.SubmissionId = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetUuid(v string) {
	o.Uuid = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetEmail(v string) {
	o.Email = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetSlug(v string) {
	o.Slug = &v
}

// GetSentAt returns the SentAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubmissionWebhookRequestDataSubmittersInner) GetSentAt() string {
	if o == nil || IsNil(o.SentAt.Get()) {
		var ret string
		return ret
	}
	return *o.SentAt.Get()
}

// GetSentAtOk returns a tuple with the SentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionWebhookRequestDataSubmittersInner) GetSentAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SentAt.Get(), o.SentAt.IsSet()
}

// HasSentAt returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasSentAt() bool {
	if o != nil && o.SentAt.IsSet() {
		return true
	}

	return false
}

// SetSentAt gets a reference to the given NullableString and assigns it to the SentAt field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetSentAt(v string) {
	o.SentAt.Set(&v)
}

// SetSentAtNil sets the value for SentAt to be an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) SetSentAtNil() {
	o.SentAt.Set(nil)
}

// UnsetSentAt ensures that no value is present for SentAt, not even an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) UnsetSentAt() {
	o.SentAt.Unset()
}

// GetOpenedAt returns the OpenedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubmissionWebhookRequestDataSubmittersInner) GetOpenedAt() string {
	if o == nil || IsNil(o.OpenedAt.Get()) {
		var ret string
		return ret
	}
	return *o.OpenedAt.Get()
}

// GetOpenedAtOk returns a tuple with the OpenedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionWebhookRequestDataSubmittersInner) GetOpenedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpenedAt.Get(), o.OpenedAt.IsSet()
}

// HasOpenedAt returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasOpenedAt() bool {
	if o != nil && o.OpenedAt.IsSet() {
		return true
	}

	return false
}

// SetOpenedAt gets a reference to the given NullableString and assigns it to the OpenedAt field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetOpenedAt(v string) {
	o.OpenedAt.Set(&v)
}

// SetOpenedAtNil sets the value for OpenedAt to be an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) SetOpenedAtNil() {
	o.OpenedAt.Set(nil)
}

// UnsetOpenedAt ensures that no value is present for OpenedAt, not even an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) UnsetOpenedAt() {
	o.OpenedAt.Unset()
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubmissionWebhookRequestDataSubmittersInner) GetCompletedAt() string {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionWebhookRequestDataSubmittersInner) GetCompletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableString and assigns it to the CompletedAt field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetCompletedAt(v string) {
	o.CompletedAt.Set(&v)
}

// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetDeclinedAt returns the DeclinedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubmissionWebhookRequestDataSubmittersInner) GetDeclinedAt() string {
	if o == nil || IsNil(o.DeclinedAt.Get()) {
		var ret string
		return ret
	}
	return *o.DeclinedAt.Get()
}

// GetDeclinedAtOk returns a tuple with the DeclinedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionWebhookRequestDataSubmittersInner) GetDeclinedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeclinedAt.Get(), o.DeclinedAt.IsSet()
}

// HasDeclinedAt returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasDeclinedAt() bool {
	if o != nil && o.DeclinedAt.IsSet() {
		return true
	}

	return false
}

// SetDeclinedAt gets a reference to the given NullableString and assigns it to the DeclinedAt field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetDeclinedAt(v string) {
	o.DeclinedAt.Set(&v)
}

// SetDeclinedAtNil sets the value for DeclinedAt to be an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) SetDeclinedAtNil() {
	o.DeclinedAt.Set(nil)
}

// UnsetDeclinedAt ensures that no value is present for DeclinedAt, not even an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) UnsetDeclinedAt() {
	o.DeclinedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubmissionWebhookRequestDataSubmittersInner) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionWebhookRequestDataSubmittersInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) UnsetName() {
	o.Name.Unset()
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetPhone(v string) {
	o.Phone = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetRole(v string) {
	o.Role = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SubmissionWebhookRequestDataSubmittersInner) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SubmissionWebhookRequestDataSubmittersInner) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *SubmissionWebhookRequestDataSubmittersInner) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetStatus(v string) {
	o.Status = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetValues() map[string]interface{} {
	if o == nil || IsNil(o.Values) {
		var ret map[string]interface{}
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetValuesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Values) {
		return map[string]interface{}{}, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]interface{} and assigns it to the Values field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetValues(v map[string]interface{}) {
	o.Values = v
}

// GetDocuments returns the Documents field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetDocuments() []FormWebhookRequestDataDocumentsInner {
	if o == nil || IsNil(o.Documents) {
		var ret []FormWebhookRequestDataDocumentsInner
		return ret
	}
	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetDocumentsOk() ([]FormWebhookRequestDataDocumentsInner, bool) {
	if o == nil || IsNil(o.Documents) {
		return nil, false
	}
	return o.Documents, true
}

// HasDocuments returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasDocuments() bool {
	if o != nil && !IsNil(o.Documents) {
		return true
	}

	return false
}

// SetDocuments gets a reference to the given []FormWebhookRequestDataDocumentsInner and assigns it to the Documents field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetDocuments(v []FormWebhookRequestDataDocumentsInner) {
	o.Documents = v
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetPreferences() map[string]interface{} {
	if o == nil || IsNil(o.Preferences) {
		var ret map[string]interface{}
		return ret
	}
	return o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) GetPreferencesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Preferences) {
		return map[string]interface{}{}, false
	}
	return o.Preferences, true
}

// HasPreferences returns a boolean if a field has been set.
func (o *SubmissionWebhookRequestDataSubmittersInner) HasPreferences() bool {
	if o != nil && !IsNil(o.Preferences) {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given map[string]interface{} and assigns it to the Preferences field.
func (o *SubmissionWebhookRequestDataSubmittersInner) SetPreferences(v map[string]interface{}) {
	o.Preferences = v
}

func (o SubmissionWebhookRequestDataSubmittersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmissionWebhookRequestDataSubmittersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SubmissionId) {
		toSerialize["submission_id"] = o.SubmissionId
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if o.SentAt.IsSet() {
		toSerialize["sent_at"] = o.SentAt.Get()
	}
	if o.OpenedAt.IsSet() {
		toSerialize["opened_at"] = o.OpenedAt.Get()
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	if o.DeclinedAt.IsSet() {
		toSerialize["declined_at"] = o.DeclinedAt.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if o.ExternalId.IsSet() {
		toSerialize["external_id"] = o.ExternalId.Get()
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.Documents) {
		toSerialize["documents"] = o.Documents
	}
	if !IsNil(o.Preferences) {
		toSerialize["preferences"] = o.Preferences
	}
	return toSerialize, nil
}

type NullableSubmissionWebhookRequestDataSubmittersInner struct {
	value *SubmissionWebhookRequestDataSubmittersInner
	isSet bool
}

func (v NullableSubmissionWebhookRequestDataSubmittersInner) Get() *SubmissionWebhookRequestDataSubmittersInner {
	return v.value
}

func (v *NullableSubmissionWebhookRequestDataSubmittersInner) Set(val *SubmissionWebhookRequestDataSubmittersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmissionWebhookRequestDataSubmittersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmissionWebhookRequestDataSubmittersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmissionWebhookRequestDataSubmittersInner(val *SubmissionWebhookRequestDataSubmittersInner) *NullableSubmissionWebhookRequestDataSubmittersInner {
	return &NullableSubmissionWebhookRequestDataSubmittersInner{value: val, isSet: true}
}

func (v NullableSubmissionWebhookRequestDataSubmittersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmissionWebhookRequestDataSubmittersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
