/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TemplateSchemaDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateSchemaDocument{}

// TemplateSchemaDocument struct for TemplateSchemaDocument
type TemplateSchemaDocument struct {
	// Unique identifier of attached document to the template.
	AttachmentUuid string `json:"attachment_uuid"`
	// Name of the attached document to the template.
	Name string `json:"name"`
}

type _TemplateSchemaDocument TemplateSchemaDocument

// NewTemplateSchemaDocument instantiates a new TemplateSchemaDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateSchemaDocument(attachmentUuid string, name string) *TemplateSchemaDocument {
	this := TemplateSchemaDocument{}
	this.AttachmentUuid = attachmentUuid
	this.Name = name
	return &this
}

// NewTemplateSchemaDocumentWithDefaults instantiates a new TemplateSchemaDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateSchemaDocumentWithDefaults() *TemplateSchemaDocument {
	this := TemplateSchemaDocument{}
	return &this
}

// GetAttachmentUuid returns the AttachmentUuid field value
func (o *TemplateSchemaDocument) GetAttachmentUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttachmentUuid
}

// GetAttachmentUuidOk returns a tuple with the AttachmentUuid field value
// and a boolean to check if the value has been set.
func (o *TemplateSchemaDocument) GetAttachmentUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttachmentUuid, true
}

// SetAttachmentUuid sets field value
func (o *TemplateSchemaDocument) SetAttachmentUuid(v string) {
	o.AttachmentUuid = v
}

// GetName returns the Name field value
func (o *TemplateSchemaDocument) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TemplateSchemaDocument) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TemplateSchemaDocument) SetName(v string) {
	o.Name = v
}

func (o TemplateSchemaDocument) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateSchemaDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attachment_uuid"] = o.AttachmentUuid
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *TemplateSchemaDocument) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attachment_uuid",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateSchemaDocument := _TemplateSchemaDocument{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateSchemaDocument)

	if err != nil {
		return err
	}

	*o = TemplateSchemaDocument(varTemplateSchemaDocument)

	return err
}

type NullableTemplateSchemaDocument struct {
	value *TemplateSchemaDocument
	isSet bool
}

func (v NullableTemplateSchemaDocument) Get() *TemplateSchemaDocument {
	return v.value
}

func (v *NullableTemplateSchemaDocument) Set(val *TemplateSchemaDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateSchemaDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateSchemaDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateSchemaDocument(val *TemplateSchemaDocument) *NullableTemplateSchemaDocument {
	return &NullableTemplateSchemaDocument{value: val, isSet: true}
}

func (v NullableTemplateSchemaDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateSchemaDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
