/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the TemplateWebhookRequestDataFieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateWebhookRequestDataFieldsInner{}

// TemplateWebhookRequestDataFieldsInner struct for TemplateWebhookRequestDataFieldsInner
type TemplateWebhookRequestDataFieldsInner struct {
	// The field UUID.
	Uuid *string `json:"uuid,omitempty"`
	// The submitter role UUID.
	SubmitterUuid *string `json:"submitter_uuid,omitempty"`
	// The field name.
	Name *string `json:"name,omitempty"`
	// The field type.
	Type *string `json:"type,omitempty"`
	// The flag indicating whether the field is required.
	Required *bool `json:"required,omitempty"`
	// The field preferences.
	Preferences map[string]interface{} `json:"preferences,omitempty"`
	// List of areas where the field is located in the document.
	Areas []TemplateWebhookRequestDataFieldsInnerAreasInner `json:"areas,omitempty"`
}

// NewTemplateWebhookRequestDataFieldsInner instantiates a new TemplateWebhookRequestDataFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateWebhookRequestDataFieldsInner() *TemplateWebhookRequestDataFieldsInner {
	this := TemplateWebhookRequestDataFieldsInner{}
	return &this
}

// NewTemplateWebhookRequestDataFieldsInnerWithDefaults instantiates a new TemplateWebhookRequestDataFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateWebhookRequestDataFieldsInnerWithDefaults() *TemplateWebhookRequestDataFieldsInner {
	this := TemplateWebhookRequestDataFieldsInner{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInner) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInner) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInner) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *TemplateWebhookRequestDataFieldsInner) SetUuid(v string) {
	o.Uuid = &v
}

// GetSubmitterUuid returns the SubmitterUuid field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInner) GetSubmitterUuid() string {
	if o == nil || IsNil(o.SubmitterUuid) {
		var ret string
		return ret
	}
	return *o.SubmitterUuid
}

// GetSubmitterUuidOk returns a tuple with the SubmitterUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInner) GetSubmitterUuidOk() (*string, bool) {
	if o == nil || IsNil(o.SubmitterUuid) {
		return nil, false
	}
	return o.SubmitterUuid, true
}

// HasSubmitterUuid returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInner) HasSubmitterUuid() bool {
	if o != nil && !IsNil(o.SubmitterUuid) {
		return true
	}

	return false
}

// SetSubmitterUuid gets a reference to the given string and assigns it to the SubmitterUuid field.
func (o *TemplateWebhookRequestDataFieldsInner) SetSubmitterUuid(v string) {
	o.SubmitterUuid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TemplateWebhookRequestDataFieldsInner) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TemplateWebhookRequestDataFieldsInner) SetType(v string) {
	o.Type = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInner) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInner) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInner) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *TemplateWebhookRequestDataFieldsInner) SetRequired(v bool) {
	o.Required = &v
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInner) GetPreferences() map[string]interface{} {
	if o == nil || IsNil(o.Preferences) {
		var ret map[string]interface{}
		return ret
	}
	return o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInner) GetPreferencesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Preferences) {
		return map[string]interface{}{}, false
	}
	return o.Preferences, true
}

// HasPreferences returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInner) HasPreferences() bool {
	if o != nil && !IsNil(o.Preferences) {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given map[string]interface{} and assigns it to the Preferences field.
func (o *TemplateWebhookRequestDataFieldsInner) SetPreferences(v map[string]interface{}) {
	o.Preferences = v
}

// GetAreas returns the Areas field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInner) GetAreas() []TemplateWebhookRequestDataFieldsInnerAreasInner {
	if o == nil || IsNil(o.Areas) {
		var ret []TemplateWebhookRequestDataFieldsInnerAreasInner
		return ret
	}
	return o.Areas
}

// GetAreasOk returns a tuple with the Areas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInner) GetAreasOk() ([]TemplateWebhookRequestDataFieldsInnerAreasInner, bool) {
	if o == nil || IsNil(o.Areas) {
		return nil, false
	}
	return o.Areas, true
}

// HasAreas returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInner) HasAreas() bool {
	if o != nil && !IsNil(o.Areas) {
		return true
	}

	return false
}

// SetAreas gets a reference to the given []TemplateWebhookRequestDataFieldsInnerAreasInner and assigns it to the Areas field.
func (o *TemplateWebhookRequestDataFieldsInner) SetAreas(v []TemplateWebhookRequestDataFieldsInnerAreasInner) {
	o.Areas = v
}

func (o TemplateWebhookRequestDataFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateWebhookRequestDataFieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.SubmitterUuid) {
		toSerialize["submitter_uuid"] = o.SubmitterUuid
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Preferences) {
		toSerialize["preferences"] = o.Preferences
	}
	if !IsNil(o.Areas) {
		toSerialize["areas"] = o.Areas
	}
	return toSerialize, nil
}

type NullableTemplateWebhookRequestDataFieldsInner struct {
	value *TemplateWebhookRequestDataFieldsInner
	isSet bool
}

func (v NullableTemplateWebhookRequestDataFieldsInner) Get() *TemplateWebhookRequestDataFieldsInner {
	return v.value
}

func (v *NullableTemplateWebhookRequestDataFieldsInner) Set(val *TemplateWebhookRequestDataFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateWebhookRequestDataFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateWebhookRequestDataFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateWebhookRequestDataFieldsInner(val *TemplateWebhookRequestDataFieldsInner) *NullableTemplateWebhookRequestDataFieldsInner {
	return &NullableTemplateWebhookRequestDataFieldsInner{value: val, isSet: true}
}

func (v NullableTemplateWebhookRequestDataFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateWebhookRequestDataFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
