/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the TemplateWebhookRequestDataSubmittersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateWebhookRequestDataSubmittersInner{}

// TemplateWebhookRequestDataSubmittersInner struct for TemplateWebhookRequestDataSubmittersInner
type TemplateWebhookRequestDataSubmittersInner struct {
	// Submitter name.
	Name *string `json:"name,omitempty"`
	// Unique identifier of the submitter.
	Uuid *string `json:"uuid,omitempty"`
}

// NewTemplateWebhookRequestDataSubmittersInner instantiates a new TemplateWebhookRequestDataSubmittersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateWebhookRequestDataSubmittersInner() *TemplateWebhookRequestDataSubmittersInner {
	this := TemplateWebhookRequestDataSubmittersInner{}
	return &this
}

// NewTemplateWebhookRequestDataSubmittersInnerWithDefaults instantiates a new TemplateWebhookRequestDataSubmittersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateWebhookRequestDataSubmittersInnerWithDefaults() *TemplateWebhookRequestDataSubmittersInner {
	this := TemplateWebhookRequestDataSubmittersInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataSubmittersInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataSubmittersInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataSubmittersInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TemplateWebhookRequestDataSubmittersInner) SetName(v string) {
	o.Name = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataSubmittersInner) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataSubmittersInner) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataSubmittersInner) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *TemplateWebhookRequestDataSubmittersInner) SetUuid(v string) {
	o.Uuid = &v
}

func (o TemplateWebhookRequestDataSubmittersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateWebhookRequestDataSubmittersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	return toSerialize, nil
}

type NullableTemplateWebhookRequestDataSubmittersInner struct {
	value *TemplateWebhookRequestDataSubmittersInner
	isSet bool
}

func (v NullableTemplateWebhookRequestDataSubmittersInner) Get() *TemplateWebhookRequestDataSubmittersInner {
	return v.value
}

func (v *NullableTemplateWebhookRequestDataSubmittersInner) Set(val *TemplateWebhookRequestDataSubmittersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateWebhookRequestDataSubmittersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateWebhookRequestDataSubmittersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateWebhookRequestDataSubmittersInner(val *TemplateWebhookRequestDataSubmittersInner) *NullableTemplateWebhookRequestDataSubmittersInner {
	return &NullableTemplateWebhookRequestDataSubmittersInner{value: val, isSet: true}
}

func (v NullableTemplateWebhookRequestDataSubmittersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateWebhookRequestDataSubmittersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
