/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the TemplateWebhookRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateWebhookRequestData{}

// TemplateWebhookRequestData Submitted data object.
type TemplateWebhookRequestData struct {
	// The template's unique identifier.
	Id *float32 `json:"id,omitempty"`
	// The template's unique slug.
	Slug *string `json:"slug,omitempty"`
	// The template's name.
	Name *string `json:"name,omitempty"`
	// The template document files.
	Schema []CreateSubmissionFromPdfResponseSchemaInner `json:"schema,omitempty"`
	// The template fields.
	Fields []TemplateWebhookRequestDataFieldsInner `json:"fields,omitempty"`
	// List of submitter roles defined in the template.
	Submitters []TemplateWebhookRequestDataSubmittersInner `json:"submitters,omitempty"`
	// Unique identifier of the author of the template.
	AuthorId *int32 `json:"author_id,omitempty"`
	// Date and time when the template was archived.
	ArchivedAt NullableString `json:"archived_at,omitempty"`
	// Date and time when the template was created.
	CreatedAt *string `json:"created_at,omitempty"`
	// Date and time when the template was updated.
	UpdatedAt *string `json:"updated_at,omitempty"`
	// Source of the template.
	Source *string `json:"source,omitempty"`
	// Identifier of the template in the external system.
	ExternalId *string `json:"external_id,omitempty"`
	// Unique identifier of the folder where the template is placed.
	FolderId *int32 `json:"folder_id,omitempty"`
	// Folder name where the template is placed.
	FolderName *string `json:"folder_name,omitempty"`
	// Template preferences object.
	Preferences map[string]interface{} `json:"preferences,omitempty"`
	// Flag indicating whether the shared link is enabled for the template.
	SharedLink *bool                                      `json:"shared_link,omitempty"`
	Author     *SubmissionWebhookRequestDataCreatedByUser `json:"author,omitempty"`
	// List of documents attached to the template.
	Documents []TemplateWebhookRequestDataDocumentsInner `json:"documents,omitempty"`
}

// NewTemplateWebhookRequestData instantiates a new TemplateWebhookRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateWebhookRequestData() *TemplateWebhookRequestData {
	this := TemplateWebhookRequestData{}
	return &this
}

// NewTemplateWebhookRequestDataWithDefaults instantiates a new TemplateWebhookRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateWebhookRequestDataWithDefaults() *TemplateWebhookRequestData {
	this := TemplateWebhookRequestData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *TemplateWebhookRequestData) SetId(v float32) {
	o.Id = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *TemplateWebhookRequestData) SetSlug(v string) {
	o.Slug = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TemplateWebhookRequestData) SetName(v string) {
	o.Name = &v
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetSchema() []CreateSubmissionFromPdfResponseSchemaInner {
	if o == nil || IsNil(o.Schema) {
		var ret []CreateSubmissionFromPdfResponseSchemaInner
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetSchemaOk() ([]CreateSubmissionFromPdfResponseSchemaInner, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given []CreateSubmissionFromPdfResponseSchemaInner and assigns it to the Schema field.
func (o *TemplateWebhookRequestData) SetSchema(v []CreateSubmissionFromPdfResponseSchemaInner) {
	o.Schema = v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetFields() []TemplateWebhookRequestDataFieldsInner {
	if o == nil || IsNil(o.Fields) {
		var ret []TemplateWebhookRequestDataFieldsInner
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetFieldsOk() ([]TemplateWebhookRequestDataFieldsInner, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []TemplateWebhookRequestDataFieldsInner and assigns it to the Fields field.
func (o *TemplateWebhookRequestData) SetFields(v []TemplateWebhookRequestDataFieldsInner) {
	o.Fields = v
}

// GetSubmitters returns the Submitters field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetSubmitters() []TemplateWebhookRequestDataSubmittersInner {
	if o == nil || IsNil(o.Submitters) {
		var ret []TemplateWebhookRequestDataSubmittersInner
		return ret
	}
	return o.Submitters
}

// GetSubmittersOk returns a tuple with the Submitters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetSubmittersOk() ([]TemplateWebhookRequestDataSubmittersInner, bool) {
	if o == nil || IsNil(o.Submitters) {
		return nil, false
	}
	return o.Submitters, true
}

// HasSubmitters returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasSubmitters() bool {
	if o != nil && !IsNil(o.Submitters) {
		return true
	}

	return false
}

// SetSubmitters gets a reference to the given []TemplateWebhookRequestDataSubmittersInner and assigns it to the Submitters field.
func (o *TemplateWebhookRequestData) SetSubmitters(v []TemplateWebhookRequestDataSubmittersInner) {
	o.Submitters = v
}

// GetAuthorId returns the AuthorId field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetAuthorId() int32 {
	if o == nil || IsNil(o.AuthorId) {
		var ret int32
		return ret
	}
	return *o.AuthorId
}

// GetAuthorIdOk returns a tuple with the AuthorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetAuthorIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AuthorId) {
		return nil, false
	}
	return o.AuthorId, true
}

// HasAuthorId returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasAuthorId() bool {
	if o != nil && !IsNil(o.AuthorId) {
		return true
	}

	return false
}

// SetAuthorId gets a reference to the given int32 and assigns it to the AuthorId field.
func (o *TemplateWebhookRequestData) SetAuthorId(v int32) {
	o.AuthorId = &v
}

// GetArchivedAt returns the ArchivedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateWebhookRequestData) GetArchivedAt() string {
	if o == nil || IsNil(o.ArchivedAt.Get()) {
		var ret string
		return ret
	}
	return *o.ArchivedAt.Get()
}

// GetArchivedAtOk returns a tuple with the ArchivedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateWebhookRequestData) GetArchivedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArchivedAt.Get(), o.ArchivedAt.IsSet()
}

// HasArchivedAt returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasArchivedAt() bool {
	if o != nil && o.ArchivedAt.IsSet() {
		return true
	}

	return false
}

// SetArchivedAt gets a reference to the given NullableString and assigns it to the ArchivedAt field.
func (o *TemplateWebhookRequestData) SetArchivedAt(v string) {
	o.ArchivedAt.Set(&v)
}

// SetArchivedAtNil sets the value for ArchivedAt to be an explicit nil
func (o *TemplateWebhookRequestData) SetArchivedAtNil() {
	o.ArchivedAt.Set(nil)
}

// UnsetArchivedAt ensures that no value is present for ArchivedAt, not even an explicit nil
func (o *TemplateWebhookRequestData) UnsetArchivedAt() {
	o.ArchivedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *TemplateWebhookRequestData) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *TemplateWebhookRequestData) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *TemplateWebhookRequestData) SetSource(v string) {
	o.Source = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *TemplateWebhookRequestData) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetFolderId returns the FolderId field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetFolderId() int32 {
	if o == nil || IsNil(o.FolderId) {
		var ret int32
		return ret
	}
	return *o.FolderId
}

// GetFolderIdOk returns a tuple with the FolderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetFolderIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FolderId) {
		return nil, false
	}
	return o.FolderId, true
}

// HasFolderId returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasFolderId() bool {
	if o != nil && !IsNil(o.FolderId) {
		return true
	}

	return false
}

// SetFolderId gets a reference to the given int32 and assigns it to the FolderId field.
func (o *TemplateWebhookRequestData) SetFolderId(v int32) {
	o.FolderId = &v
}

// GetFolderName returns the FolderName field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetFolderName() string {
	if o == nil || IsNil(o.FolderName) {
		var ret string
		return ret
	}
	return *o.FolderName
}

// GetFolderNameOk returns a tuple with the FolderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetFolderNameOk() (*string, bool) {
	if o == nil || IsNil(o.FolderName) {
		return nil, false
	}
	return o.FolderName, true
}

// HasFolderName returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasFolderName() bool {
	if o != nil && !IsNil(o.FolderName) {
		return true
	}

	return false
}

// SetFolderName gets a reference to the given string and assigns it to the FolderName field.
func (o *TemplateWebhookRequestData) SetFolderName(v string) {
	o.FolderName = &v
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetPreferences() map[string]interface{} {
	if o == nil || IsNil(o.Preferences) {
		var ret map[string]interface{}
		return ret
	}
	return o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetPreferencesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Preferences) {
		return map[string]interface{}{}, false
	}
	return o.Preferences, true
}

// HasPreferences returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasPreferences() bool {
	if o != nil && !IsNil(o.Preferences) {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given map[string]interface{} and assigns it to the Preferences field.
func (o *TemplateWebhookRequestData) SetPreferences(v map[string]interface{}) {
	o.Preferences = v
}

// GetSharedLink returns the SharedLink field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetSharedLink() bool {
	if o == nil || IsNil(o.SharedLink) {
		var ret bool
		return ret
	}
	return *o.SharedLink
}

// GetSharedLinkOk returns a tuple with the SharedLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetSharedLinkOk() (*bool, bool) {
	if o == nil || IsNil(o.SharedLink) {
		return nil, false
	}
	return o.SharedLink, true
}

// HasSharedLink returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasSharedLink() bool {
	if o != nil && !IsNil(o.SharedLink) {
		return true
	}

	return false
}

// SetSharedLink gets a reference to the given bool and assigns it to the SharedLink field.
func (o *TemplateWebhookRequestData) SetSharedLink(v bool) {
	o.SharedLink = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetAuthor() SubmissionWebhookRequestDataCreatedByUser {
	if o == nil || IsNil(o.Author) {
		var ret SubmissionWebhookRequestDataCreatedByUser
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetAuthorOk() (*SubmissionWebhookRequestDataCreatedByUser, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given SubmissionWebhookRequestDataCreatedByUser and assigns it to the Author field.
func (o *TemplateWebhookRequestData) SetAuthor(v SubmissionWebhookRequestDataCreatedByUser) {
	o.Author = &v
}

// GetDocuments returns the Documents field value if set, zero value otherwise.
func (o *TemplateWebhookRequestData) GetDocuments() []TemplateWebhookRequestDataDocumentsInner {
	if o == nil || IsNil(o.Documents) {
		var ret []TemplateWebhookRequestDataDocumentsInner
		return ret
	}
	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestData) GetDocumentsOk() ([]TemplateWebhookRequestDataDocumentsInner, bool) {
	if o == nil || IsNil(o.Documents) {
		return nil, false
	}
	return o.Documents, true
}

// HasDocuments returns a boolean if a field has been set.
func (o *TemplateWebhookRequestData) HasDocuments() bool {
	if o != nil && !IsNil(o.Documents) {
		return true
	}

	return false
}

// SetDocuments gets a reference to the given []TemplateWebhookRequestDataDocumentsInner and assigns it to the Documents field.
func (o *TemplateWebhookRequestData) SetDocuments(v []TemplateWebhookRequestDataDocumentsInner) {
	o.Documents = v
}

func (o TemplateWebhookRequestData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateWebhookRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Submitters) {
		toSerialize["submitters"] = o.Submitters
	}
	if !IsNil(o.AuthorId) {
		toSerialize["author_id"] = o.AuthorId
	}
	if o.ArchivedAt.IsSet() {
		toSerialize["archived_at"] = o.ArchivedAt.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !IsNil(o.FolderId) {
		toSerialize["folder_id"] = o.FolderId
	}
	if !IsNil(o.FolderName) {
		toSerialize["folder_name"] = o.FolderName
	}
	if !IsNil(o.Preferences) {
		toSerialize["preferences"] = o.Preferences
	}
	if !IsNil(o.SharedLink) {
		toSerialize["shared_link"] = o.SharedLink
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Documents) {
		toSerialize["documents"] = o.Documents
	}
	return toSerialize, nil
}

type NullableTemplateWebhookRequestData struct {
	value *TemplateWebhookRequestData
	isSet bool
}

func (v NullableTemplateWebhookRequestData) Get() *TemplateWebhookRequestData {
	return v.value
}

func (v *NullableTemplateWebhookRequestData) Set(val *TemplateWebhookRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateWebhookRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateWebhookRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateWebhookRequestData(val *TemplateWebhookRequestData) *NullableTemplateWebhookRequestData {
	return &NullableTemplateWebhookRequestData{value: val, isSet: true}
}

func (v NullableTemplateWebhookRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateWebhookRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
