/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the TemplateWebhookRequestDataFieldsInnerAreasInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateWebhookRequestDataFieldsInnerAreasInner{}

// TemplateWebhookRequestDataFieldsInnerAreasInner struct for TemplateWebhookRequestDataFieldsInnerAreasInner
type TemplateWebhookRequestDataFieldsInnerAreasInner struct {
	// X coordinate of the area where the field is located in the document.
	X *float32 `json:"x,omitempty"`
	// Y coordinate of the area where the field is located in the document.
	Y *float32 `json:"y,omitempty"`
	// Width of the area where the field is located in the document.
	W *float32 `json:"w,omitempty"`
	// Height of the area where the field is located in the document.
	H *float32 `json:"h,omitempty"`
	// Unique identifier of the attached document where the field is located.
	AttachmentUuid *string `json:"attachment_uuid,omitempty"`
	// Page number of the attached document where the field is located.
	Page *int32 `json:"page,omitempty"`
}

// NewTemplateWebhookRequestDataFieldsInnerAreasInner instantiates a new TemplateWebhookRequestDataFieldsInnerAreasInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateWebhookRequestDataFieldsInnerAreasInner() *TemplateWebhookRequestDataFieldsInnerAreasInner {
	this := TemplateWebhookRequestDataFieldsInnerAreasInner{}
	return &this
}

// NewTemplateWebhookRequestDataFieldsInnerAreasInnerWithDefaults instantiates a new TemplateWebhookRequestDataFieldsInnerAreasInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateWebhookRequestDataFieldsInnerAreasInnerWithDefaults() *TemplateWebhookRequestDataFieldsInnerAreasInner {
	this := TemplateWebhookRequestDataFieldsInnerAreasInner{}
	return &this
}

// GetX returns the X field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetX() float32 {
	if o == nil || IsNil(o.X) {
		var ret float32
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetXOk() (*float32, bool) {
	if o == nil || IsNil(o.X) {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) HasX() bool {
	if o != nil && !IsNil(o.X) {
		return true
	}

	return false
}

// SetX gets a reference to the given float32 and assigns it to the X field.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) SetX(v float32) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetY() float32 {
	if o == nil || IsNil(o.Y) {
		var ret float32
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetYOk() (*float32, bool) {
	if o == nil || IsNil(o.Y) {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) HasY() bool {
	if o != nil && !IsNil(o.Y) {
		return true
	}

	return false
}

// SetY gets a reference to the given float32 and assigns it to the Y field.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) SetY(v float32) {
	o.Y = &v
}

// GetW returns the W field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetW() float32 {
	if o == nil || IsNil(o.W) {
		var ret float32
		return ret
	}
	return *o.W
}

// GetWOk returns a tuple with the W field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetWOk() (*float32, bool) {
	if o == nil || IsNil(o.W) {
		return nil, false
	}
	return o.W, true
}

// HasW returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) HasW() bool {
	if o != nil && !IsNil(o.W) {
		return true
	}

	return false
}

// SetW gets a reference to the given float32 and assigns it to the W field.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) SetW(v float32) {
	o.W = &v
}

// GetH returns the H field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetH() float32 {
	if o == nil || IsNil(o.H) {
		var ret float32
		return ret
	}
	return *o.H
}

// GetHOk returns a tuple with the H field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetHOk() (*float32, bool) {
	if o == nil || IsNil(o.H) {
		return nil, false
	}
	return o.H, true
}

// HasH returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) HasH() bool {
	if o != nil && !IsNil(o.H) {
		return true
	}

	return false
}

// SetH gets a reference to the given float32 and assigns it to the H field.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) SetH(v float32) {
	o.H = &v
}

// GetAttachmentUuid returns the AttachmentUuid field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetAttachmentUuid() string {
	if o == nil || IsNil(o.AttachmentUuid) {
		var ret string
		return ret
	}
	return *o.AttachmentUuid
}

// GetAttachmentUuidOk returns a tuple with the AttachmentUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetAttachmentUuidOk() (*string, bool) {
	if o == nil || IsNil(o.AttachmentUuid) {
		return nil, false
	}
	return o.AttachmentUuid, true
}

// HasAttachmentUuid returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) HasAttachmentUuid() bool {
	if o != nil && !IsNil(o.AttachmentUuid) {
		return true
	}

	return false
}

// SetAttachmentUuid gets a reference to the given string and assigns it to the AttachmentUuid field.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) SetAttachmentUuid(v string) {
	o.AttachmentUuid = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *TemplateWebhookRequestDataFieldsInnerAreasInner) SetPage(v int32) {
	o.Page = &v
}

func (o TemplateWebhookRequestDataFieldsInnerAreasInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateWebhookRequestDataFieldsInnerAreasInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.X) {
		toSerialize["x"] = o.X
	}
	if !IsNil(o.Y) {
		toSerialize["y"] = o.Y
	}
	if !IsNil(o.W) {
		toSerialize["w"] = o.W
	}
	if !IsNil(o.H) {
		toSerialize["h"] = o.H
	}
	if !IsNil(o.AttachmentUuid) {
		toSerialize["attachment_uuid"] = o.AttachmentUuid
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullableTemplateWebhookRequestDataFieldsInnerAreasInner struct {
	value *TemplateWebhookRequestDataFieldsInnerAreasInner
	isSet bool
}

func (v NullableTemplateWebhookRequestDataFieldsInnerAreasInner) Get() *TemplateWebhookRequestDataFieldsInnerAreasInner {
	return v.value
}

func (v *NullableTemplateWebhookRequestDataFieldsInnerAreasInner) Set(val *TemplateWebhookRequestDataFieldsInnerAreasInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateWebhookRequestDataFieldsInnerAreasInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateWebhookRequestDataFieldsInnerAreasInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateWebhookRequestDataFieldsInnerAreasInner(val *TemplateWebhookRequestDataFieldsInnerAreasInner) *NullableTemplateWebhookRequestDataFieldsInnerAreasInner {
	return &NullableTemplateWebhookRequestDataFieldsInnerAreasInner{value: val, isSet: true}
}

func (v NullableTemplateWebhookRequestDataFieldsInnerAreasInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateWebhookRequestDataFieldsInnerAreasInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
