/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"
)

// checks if the TemplateWebhookRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateWebhookRequest{}

// TemplateWebhookRequest struct for TemplateWebhookRequest
type TemplateWebhookRequest struct {
	// The event type.
	EventType *string `json:"event_type,omitempty"`
	// The event timestamp.
	Timestamp *time.Time                  `json:"timestamp,omitempty"`
	Data      *TemplateWebhookRequestData `json:"data,omitempty"`
}

// NewTemplateWebhookRequest instantiates a new TemplateWebhookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateWebhookRequest() *TemplateWebhookRequest {
	this := TemplateWebhookRequest{}
	return &this
}

// NewTemplateWebhookRequestWithDefaults instantiates a new TemplateWebhookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateWebhookRequestWithDefaults() *TemplateWebhookRequest {
	this := TemplateWebhookRequest{}
	return &this
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *TemplateWebhookRequest) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequest) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *TemplateWebhookRequest) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *TemplateWebhookRequest) SetEventType(v string) {
	o.EventType = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *TemplateWebhookRequest) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequest) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *TemplateWebhookRequest) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *TemplateWebhookRequest) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TemplateWebhookRequest) GetData() TemplateWebhookRequestData {
	if o == nil || IsNil(o.Data) {
		var ret TemplateWebhookRequestData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateWebhookRequest) GetDataOk() (*TemplateWebhookRequestData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TemplateWebhookRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given TemplateWebhookRequestData and assigns it to the Data field.
func (o *TemplateWebhookRequest) SetData(v TemplateWebhookRequestData) {
	o.Data = &v
}

func (o TemplateWebhookRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateWebhookRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventType) {
		toSerialize["event_type"] = o.EventType
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableTemplateWebhookRequest struct {
	value *TemplateWebhookRequest
	isSet bool
}

func (v NullableTemplateWebhookRequest) Get() *TemplateWebhookRequest {
	return v.value
}

func (v *NullableTemplateWebhookRequest) Set(val *TemplateWebhookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateWebhookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateWebhookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateWebhookRequest(val *TemplateWebhookRequest) *NullableTemplateWebhookRequest {
	return &NullableTemplateWebhookRequest{value: val, isSet: true}
}

func (v NullableTemplateWebhookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateWebhookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
