/*
DocuSeal API

DocuSeal API specs

API version: 1.0.0
Contact: admin@docuseal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the UpdateTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTemplateRequest{}

// UpdateTemplateRequest struct for UpdateTemplateRequest
type UpdateTemplateRequest struct {
	// The name of the template.
	Name *string `json:"name,omitempty"`
	// The folder's name to which the template should be moved.
	FolderName *string `json:"folder_name,omitempty"`
	// An array of submitter role names to update the template with.
	Roles []string `json:"roles,omitempty"`
	// Set `false` to unarchive template.
	Archived *bool `json:"archived,omitempty"`
}

// NewUpdateTemplateRequest instantiates a new UpdateTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTemplateRequest() *UpdateTemplateRequest {
	this := UpdateTemplateRequest{}
	return &this
}

// NewUpdateTemplateRequestWithDefaults instantiates a new UpdateTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTemplateRequestWithDefaults() *UpdateTemplateRequest {
	this := UpdateTemplateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateTemplateRequest) SetName(v string) {
	o.Name = &v
}

// GetFolderName returns the FolderName field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetFolderName() string {
	if o == nil || IsNil(o.FolderName) {
		var ret string
		return ret
	}
	return *o.FolderName
}

// GetFolderNameOk returns a tuple with the FolderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetFolderNameOk() (*string, bool) {
	if o == nil || IsNil(o.FolderName) {
		return nil, false
	}
	return o.FolderName, true
}

// HasFolderName returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasFolderName() bool {
	if o != nil && !IsNil(o.FolderName) {
		return true
	}

	return false
}

// SetFolderName gets a reference to the given string and assigns it to the FolderName field.
func (o *UpdateTemplateRequest) SetFolderName(v string) {
	o.FolderName = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetRoles() []string {
	if o == nil || IsNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *UpdateTemplateRequest) SetRoles(v []string) {
	o.Roles = v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *UpdateTemplateRequest) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateRequest) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *UpdateTemplateRequest) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *UpdateTemplateRequest) SetArchived(v bool) {
	o.Archived = &v
}

func (o UpdateTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.FolderName) {
		toSerialize["folder_name"] = o.FolderName
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	return toSerialize, nil
}

type NullableUpdateTemplateRequest struct {
	value *UpdateTemplateRequest
	isSet bool
}

func (v NullableUpdateTemplateRequest) Get() *UpdateTemplateRequest {
	return v.value
}

func (v *NullableUpdateTemplateRequest) Set(val *UpdateTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTemplateRequest(val *UpdateTemplateRequest) *NullableUpdateTemplateRequest {
	return &NullableUpdateTemplateRequest{value: val, isSet: true}
}

func (v NullableUpdateTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
